### ISSUE TITLE
MM snap for all gas tokens

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#10253]
Edwin's investigation doc: https://docs.google.com/document/d/1WE6mJAcY90pcGdn2yqmhdaUwRxynFShCIcoy9lO8URw/edit

Github Repo: https://github.com/celo-org/gas-snap

WETH as gas token investigation: https://www.notion.so/clabsco/WETH-as-Gas-Token-WIP-2ff368a0c4484566a868000e90ecc679

```[tasklist]
### Tasks
- [x] https://github.com/celo-org/celo-monorepo/issues/10254 (1)
- [x] https://github.com/celo-org/celo-monorepo/issues/10255 (3)
- [x] https://github.com/celo-org/celo-monorepo/issues/10279 (2)
- [x] https://github.com/celo-org/celo-monorepo/issues/10278 (2)
- [x] https://github.com/celo-org/celo-monorepo/issues/10259 (2)
- [x] https://github.com/celo-org/celo-monorepo/issues/10256 (3)
- [x] https://github.com/celo-org/celo-monorepo/issues/10287 (1)
- [x] https://github.com/celo-org/celo-monorepo/issues/10305 (2)
- [x] https://github.com/celo-org/celo-monorepo/issues/10306 (1)
- [x] https://github.com/celo-org/celo-monorepo/issues/10307 (1)
- [x] https://github.com/celo-org/celo-monorepo/issues/10257 (2)
- [x] https://github.com/celo-org/celo-monorepo/issues/10316 (1)
- [ ] https://github.com/celo-org/celo-monorepo/issues/10328
- [x] https://github.com/celo-org/celo-monorepo/issues/10258 (1)
- [ ] https://github.com/celo-org/celo-monorepo/issues/10262 (3)
- [ ] https://github.com/celo-org/celo-monorepo/issues/10260 (2)
- [ ] https://github.com/celo-org/celo-monorepo/issues/10263 (3)
- [ ] https://github.com/celo-org/celo-monorepo/issues/10261 (3)
- [ ] https://github.com/celo-org/celo-monorepo/issues/10264 (2)
- [x] https://github.com/celo-org/celo-monorepo/issues/10265 (2)
- [ ] https://github.com/celo-org/celo-monorepo/issues/10407
- [ ] https://github.com/celo-org/celo-monorepo/issues/10342
- [ ] https://github.com/celo-org/celo-monorepo/issues/10343
- [ ] https://github.com/celo-org/celo-monorepo/issues/10404
- [ ] https://github.com/celo-org/celo-monorepo/issues/10405
- [ ] https://github.com/celo-org/celo-monorepo/issues/10286
- [ ] https://github.com/celo-org/celo-monorepo/issues/10417
- [ ] https://github.com/celo-org/celo-monorepo/issues/10418
- [ ] https://github.com/celo-org/celo-monorepo/issues/10419
- [ ] https://github.com/celo-org/celo-monorepo/issues/10420
- [ ] https://github.com/celo-org/celo-monorepo/issues/10426
- [ ] https://github.com/celo-org/celo-monorepo/issues/10427
- [ ] https://github.com/celo-org/celo-monorepo/issues/10432
- [ ] https://github.com/celo-org/celo-monorepo/issues/10485
- [ ] https://github.com/celo-org/celo-monorepo/issues/10492
- [ ] https://github.com/celo-org/celo-monorepo/issues/10493
- [ ] https://github.com/celo-org/celo-monorepo/issues/10494
- [ ] https://github.com/celo-org/celo-monorepo/issues/10495
- [ ] https://github.com/celo-org/celo-monorepo/issues/10497
- [ ] https://github.com/celo-org/celo-monorepo/issues/10504
- [ ] https://github.com/celo-org/celo-monorepo/issues/10505
- [ ] https://github.com/celo-org/celo-monorepo/issues/10546
```

see estimation spreadsheet for most up to date estimate: https://docs.google.com/spreadsheets/d/1iFnLHswLtJEC6wDnGA0HXjwPIE5mU9WEinkxFBe1DxM/edit?usp=sharing

Total: 27 days (gut estimate, ~ 6 weeks for 1 engineer)
 
lets say 30% uncertainty in either direction --> 19-35 days (4 - 7 weeks for 1 engineer) 
lets say with 2 engineers we go 30% faster --> 14-25 days  (**3 - 5 weeks for 2 engineers**)
