### ISSUE TITLE
snap guide / stCelo frontend integration

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#10261]
assist a front-end engineer in integrating the snap with the stCelo frontend 
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/celo-monorepo/issues/10418
- [x] Resolve validation error from Rainbowkit
- [x] Connect and install snap
- [x] Send Transaction to Snap
- [x] Integrate rainbowkit with stCelo
- [ ] https://github.com/celo-org/celo-monorepo/issues/10427
- [ ] https://github.com/celo-org/celo-monorepo/issues/10426
- [ ] https://github.com/celo-org/celo-monorepo/issues/10420
```
