### ISSUE TITLE
Create a CELO compatible fork of ganache monorepo

### ISSUE THREAD

**Issue by soloseng** [celo-org/celo-monorepo#10272]
A fork of [Ganache](https://github.com/trufflesuite/ganache) that is compatible with CELO.

```[tasklist]
### Tasks
- [x] Adding precompiles to be deployed during chain genesis
- [ ] Adding support for optional celo fee currency
- [ ] Adding support for personal decrypt
```
Related [PR](https://github.com/celo-org/ganache/pull/1)

**Comment by soloseng** [comment]
Current working branch:
https://github.com/celo-org/ganache/tree/soloseng/CELO-support

These changes have not yet been published.

**Comment by soloseng** [comment]
Original ganache-core fork did not actually support fee currency payment. 

When submitting a transaction using any stable token, the stableToken amount does not actually get decremented.

Question now is:

To what extent do we want to add that functionality to ganache? 

**NB: fee currency works properly in e2e test, when using `geth`**

**Comment by soloseng** [comment]
Released an unofficial ganache fork NPM package under the `@celo` namespace

link to the [repo](https://github.com/celo-org/ganache)
