### ISSUE TITLE
Migrate unit test to Foundry

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#10319]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/celo-monorepo/issues/10802
- [ ] https://github.com/celo-org/celo-monorepo/issues/10801
- [ ] https://github.com/celo-org/celo-monorepo/issues/10805
- [ ] https://github.com/celo-org/celo-monorepo/issues/10856
- [ ] https://github.com/celo-org/celo-monorepo/issues/10867
- [ ] https://github.com/celo-org/celo-monorepo/issues/10858
- [ ] https://github.com/celo-org/celo-monorepo/issues/10836
- [ ] https://github.com/celo-org/celo-monorepo/issues/10789
- [ ] https://github.com/celo-org/celo-monorepo/issues/10860
- [ ] https://github.com/celo-org/celo-monorepo/issues/10837
- [ ] https://github.com/celo-org/celo-monorepo/issues/10854
- [ ] https://github.com/celo-org/celo-monorepo/issues/10793
- [ ] https://github.com/celo-org/celo-monorepo/issues/10857
- [ ] https://github.com/celo-org/celo-monorepo/issues/10678
- [ ] https://github.com/celo-org/celo-monorepo/issues/10813
- [ ] https://github.com/celo-org/celo-monorepo/issues/10803
- [ ] https://github.com/celo-org/celo-monorepo/issues/10761
- [ ] https://github.com/celo-org/celo-monorepo/issues/10777
- [ ] https://github.com/celo-org/celo-monorepo/issues/10786
- [ ] https://github.com/celo-org/celo-monorepo/issues/10799
- [ ] https://github.com/celo-org/celo-monorepo/issues/10754
- [ ] https://github.com/celo-org/celo-monorepo/issues/10751
- [ ] https://github.com/celo-org/celo-monorepo/issues/10753
- [ ] https://github.com/celo-org/celo-monorepo/issues/10750
- [ ] https://github.com/celo-org/celo-monorepo/issues/10674
- [ ] https://github.com/celo-org/celo-monorepo/issues/10752
- [ ] https://github.com/celo-org/celo-monorepo/issues/10787
- [ ] https://github.com/celo-org/celo-monorepo/issues/10759
- [ ] https://github.com/celo-org/celo-monorepo/issues/10758
- [ ] https://github.com/celo-org/celo-monorepo/issues/10665
- [ ] https://github.com/celo-org/celo-monorepo/issues/10760
- [ ] https://github.com/celo-org/celo-monorepo/issues/10668
- [ ] https://github.com/celo-org/celo-monorepo/issues/10667
- [ ] https://github.com/celo-org/celo-monorepo/issues/10669
- [ ] https://github.com/celo-org/celo-monorepo/issues/10762
- [ ] https://github.com/celo-org/celo-monorepo/issues/10677
- [ ] https://github.com/celo-org/celo-monorepo/issues/10794
```

**Comment by martinvol** [comment]
Moved integration tests to this issue: https://github.com/celo-org/celo-monorepo/issues/11099

**Comment by arthurgousset** [comment]
Closing this as done since these two are done: 
- https://github.com/celo-org/celo-monorepo/issues/10802
- https://github.com/celo-org/celo-monorepo/issues/10801
