### ISSUE TITLE
Add Ultragreen functions to celocli

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#10326]
Functions should support:
* ` handle(address tokenAddress)`
*  `handleAll()`
* `distribute(address tokenAddress)`
* `distributeAll()`

As described in the CIP: https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0052.md
```[tasklist]
### Tasks
- [x] Expose functions in contract kit
- [x] Integrate to celo cli
- [ ] Add unit tests.
```

**Comment by arthurgousset** [comment]
Related pull requests:
- https://github.com/celo-org/celo-monorepo/pull/10524
- https://github.com/celo-org/celo-monorepo/pull/10403

**Comment by arthurgousset** [comment]
(for context)
The ultragreen smart contract is going live on Mainnet with the [ginger hardfork](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0062.md).

**Comment by arthurgousset** [comment]
Some additional context from @martinvol:
- UltraGreen contract is deployed and will accumulate fees after the hardfork
- first exchange will happen after it gets enabled, in a separate governance proposal
- At the moment there’s no rush to actually publish the CLI with the update

I still propose we get to work on this, so it's out of the way, but the prioritisation doesn't have to do with the Gingerbread hardfork tomorrow (Tue, Sep 26).
