### ISSUE TITLE
ODIS scalability

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#10333]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/celo-monorepo/issues/10335
- [ ] https://github.com/celo-org/celo-monorepo/issues/10392
- [ ] https://github.com/celo-org/celo-monorepo/issues/10352
- [ ] https://github.com/celo-org/celo-monorepo/issues/10150
- [ ] https://github.com/celo-org/celo-monorepo/issues/10441
- [ ] https://github.com/celo-org/celo-monorepo/issues/10334
- [ ] https://github.com/celo-org/celo-monorepo/issues/10498
- [ ] https://github.com/celo-org/celo-monorepo/issues/10499
```
