### ISSUE TITLE
snap rusty MVP integration

### ISSUE THREAD

**Issue by montera82** [celo-org/celo-monorepo#10419]
```[tasklist]
### Tasks
- [x] Snap connect and install
- [x] Modify UI to allow Stake with Snap
- [ ] Modify UI to allow unStake with Snap
- [ ] Add writeup to educate user that Flask
```

**Comment by montera82** [comment]
This is depioritized, since my front end skill do not meet up with the complexity involved.
