### ISSUE TITLE
Snap Testing bugs

### ISSUE THREAD

**Issue by montera82** [celo-org/celo-monorepo#10495]
Maintaining a list of know errors which i'll fix before sending out for internal review.

```[tasklist]
### Tasks
- [x] Snap keeps trying to install when user attempts to stake even after previoulsy installing.
- [x] Staking succeeds but we get 500 when we choose staking with cusd - even though transaction success - this happens ONLY FOR STAKING
- [x] Staking is missing the transaction submitted screen
- [x] When user rejects transaction, we still get a success screen
- [x] Test Governance path
- [x] Bolden suggested currency on currency screen
- [x] accept lower case or upper case for currency
- [x] Modify Rainbowkit to fallback to default behaviour when using MM
- [x] Fix currency validation which allows unknown currency to be provided
- [x] If user does not have a particular currency e.g cReal and keys that in the currency screen we get a wiered error
- [x] Add information on the UI that links users to information where they can install Flask and use the Gas-
- [x] user is asked to reinstall the snap 3 times if they cancel the first time
- [x] Test path where user has more cUSd than celo
- [x] error when clicking next on default currency
- [x] Fix merge conflicts on both stCelowebapp and rainbowkit and merge PRs
- [x] Change snap dialog invoke to throw errors as well as display dialogs
- [x] error when cutting off transaction on first approve screen 0xFfe124dde2b29fA848aD8caAEBE85651F0b5c406 value: 0.01 ETH data: 0xd0e30db0 Details: Cannot read properties of null (reading 'toLowerCase') Version: viem@1.2.9
- [ ] Update MVP link with latest updates of gas-snap, stcelo and rainbow
```

**Comment by montera82** [comment]
Staking succeeds but we get 500 when we choose staking with cusd - even though transaction success - ONLY FOR STAKING 

![Pasted Graphic](https://github.com/celo-org/celo-monorepo/assets/8665738/0c3ca841-af00-4e64-a9f6-ed3c54be39b7)

Staking is missing this screen 

![Pasted Graphic 4](https://github.com/celo-org/celo-monorepo/assets/8665738/d142ca2a-dd84-4571-b0dc-ebd2603ba7b0)

WHEN USER REJECTS TRANSACTION SHOWS THIS
![Pasted Graphic 1](https://github.com/celo-org/celo-monorepo/assets/8665738/5e98ef7a-832a-4d8d-87b1-c266077c5e1b)

Expectation
![Pasted Graphic 3](https://github.com/celo-org/celo-monorepo/assets/8665738/cc99a876-e4bd-48c7-9abf-2135af1019d0)

SAME FOR UNSTAKING 
![Pasted Graphic 2](https://github.com/celo-org/celo-monorepo/assets/8665738/998dbe28-dcac-4a1d-b736-774800f5a400)

When user attempts to fall back to defaut mm behaviour
![image](https://github.com/celo-org/celo-monorepo/assets/8665738/164ca05d-c533-4601-bfad-ae8f827e18c8)
