### ISSUE TITLE
Fully Test Combiner Without Proxy

### ISSUE THREAD

**Issue by soloseng** [celo-org/celo-monorepo#10611]
Run all necessary tests on the Combiner using Gen2 cloud function
```[tasklist]
### Tasks
- [x] Staging E2E test
- [x] Staging load test
- [x] Alfajores E2E test
- [x] Alfajores load test
- [x] Mainnet E2E test
- [x] Mainnet load test
```
