### ISSUE TITLE
remove protocol as dev dep of contractkit

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#10718]
several tests in contractkit use functions from @celo/protocol. refactor so this is not the case

```[tasklist]
### Tasks
- [ ] use celo/abis instead of generating from [script in protocol](https://github.com/celo-org/celo-monorepo/issues/10719)
- [ ] dont import `getParsedSignatureFromAddress` from protocol. use from contractkit
- [ ] find alternative to building devchain from script in protocol
- [ ] remove MetaTransactionWallet test which rely on files from protocol
- [ ] modify SortedOracles test which have same issue
```

**Comment by aaronmgdr** [comment]
part of https://github.com/celo-org/celo-labs/issues/1022
