### ISSUE TITLE
[Epic] Anvil Migrations

### ISSUE THREAD

**Issue by soloseng** [celo-org/celo-monorepo#10990]
Tracks the tasks related to the Anvil integration.

```[tasklist]
### Planned and scheduled
- [x] merge https://github.com/celo-org/celo-monorepo/pull/10875
- [x] validators test still doesn't work
- [x] tests are failing
- [ ] https://github.com/celo-org/celo-monorepo/issues/10991
- [ ] https://github.com/celo-org/celo-monorepo/issues/11000
- [ ] https://github.com/celo-org/celo-monorepo/issues/10999
- [ ] https://github.com/celo-org/celo-monorepo/issues/11015
- [ ] https://github.com/celo-org/celo-monorepo/issues/11022
- [ ] https://github.com/celo-org/celo-monorepo/issues/11025
- [ ] https://github.com/celo-org/celo-monorepo/issues/11026#top
- [ ] https://github.com/celo-org/celo-monorepo/issues/11032
- [x] Create a central list of core contracts in solidity
- [ ] https://github.com/celo-org/celo-monorepo/issues/11103
```

**Comment by arthurgousset** [comment]
This issue is related (but [according to Victoria](https://clabsco.slack.com/archives/C0705GMH2A1/p1715254830111239), Cel2 issues can't be tracked by multiple epics):
- https://github.com/celo-org/celo-monorepo/issues/10991

**Comment by arthurgousset** [comment]
Closing this in favour of 
- https://github.com/celo-org/celo-monorepo/issues/11147
