### ISSUE TITLE
[Epic] Replace Truffle + Ganache with Foundry suite

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#11098]
### Tests
- [ ] https://github.com/celo-org/celo-monorepo/issues/11099
- [ ] https://github.com/celo-org/celo-monorepo/issues/11156
- [ ] https://github.com/celo-org/celo-monorepo/issues/11157
- [ ] https://github.com/celo-org/celo-blockchain-planning/issues/443

Documentation for scripts can be found here: https://docs.celo.org/community/release-process/smart-contracts
Also see: https://github.com/celo-org/celo-monorepo/issues/11078

### Scripts
- [ ] https://github.com/celo-org/celo-monorepo/issues/11158
- [ ] https://github.com/celo-org/celo-monorepo/issues/11159
- [ ] https://github.com/celo-org/celo-monorepo/issues/11160
- [ ] https://github.com/celo-org/celo-monorepo/issues/11161
- [ ] https://github.com/celo-org/celo-monorepo/issues/11102
- [ ] https://github.com/celo-org/celo-monorepo/issues/11162
- [ ] https://github.com/celo-org/celo-monorepo/issues/11163
- [ ] https://github.com/celo-org/celo-monorepo/issues/11164
- [ ] https://github.com/celo-org/celo-monorepo/issues/11100
- [ ] https://github.com/celo-org/celo-monorepo/issues/11165
- [ ] https://github.com/celo-org/celo-monorepo/issues/11166

### Devchain
- [ ] https://github.com/celo-org/celo-monorepo/issues/11167
- [ ] https://github.com/celo-org/celo-monorepo/issues/11145
- [ ] https://github.com/celo-org/celo-monorepo/issues/11101
- [ ] https://github.com/celo-org/celo-monorepo/issues/10994

(@m-chrzan edit: removed tasklist syntax)

**Comment by m-chrzan** [comment]
RE: Generate types without typechain

Once everything is using Foundry (i.e. written in Solidity), we shouldn't need any type generation within the packages itself. Or is this to generate TS types for other packages/external projects to use? If so, is there a reason to not keep using TypeChain specifically?

**Comment by martinvol** [comment]
@m-chrzan Typechain is to generate types that contractkit and other third parties use

**Comment by lvpeschke** [comment]
@celo-org/primitives @martinvol please update

**Comment by martinvol** [comment]
This epic is a duplicate of https://github.com/celo-org/celo-monorepo/issues/11372
Working with the team currently to consolidate everything into one (don't know which one yet)
