### ISSUE TITLE
[Epic] List of Anvil migration improvements

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#11147]
Follow-on issues from:
- https://github.com/celo-org/celo-monorepo/issues/10990

```[tasklist]
### Tasks
- [ ] StableTokens are deployed but not all exchanges are deployed, only one exchange (Mento) is deployed
- [ ] pretify pre-commit hook breaks when comiting Solidity
- [ ] Not all precompiles implemented, need to create loop to deploy them
- [ ] script is still not split (run migrations, run with integration tests, etc)
- [ ] Initialization interfaces need to be defined
- [ ] json doesn't support full config (for example, sender keys are not configurable)
- [ ] validator deployment is oversimplied (din't think it was worth migrating the whole thing)
- [ ] Supply of eth not doesn't match what the Celo smart contract thinks it is.
- [ ] Standalone CI job to generate migrations not created.
- [ ] Consider breaking migrations.s.sol into multiple files
```
