### ISSUE TITLE
Use IPC by default in ContractKit, CLI and Docker tutorial

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#1376]
- [x] Add/verify support for IPC to ContractKit so we can supply a path to a file to connect to local geth instances with IPC enabled (ideally, make this the default)
- [x] Add support for that configuration to the CLI (and document it)
- [ ] Find out how to connect from host to Geth running IPC inside a Docker container
- [ ] Update validator and full node tutorials to use IPC rather than RPC
