### ISSUE TITLE
Test Faulty & Extreme Blockchain Conditions

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#2523]
Test celo-blockchain with different scenarios; with a focus on load, performance, random failures, extreme conditions.

This task can be divided into:

 - [x] Script to launch testnet with customizable configurations (be able to set blockchain parameters, failure nodes w/ different modes, chaos monkey conditions)
       - It's also important for this tesnets to have tx volume
       - have nodes behind proxies
 - [x] Write a test plan. This must include all scenarios that we want to test. Define Test parameters, test length, expected outputs, checks to be made.
 - [x] For each test scenario, perform tests.

Additionaly, others tasks can be:

 - [ ] Write script/automated check to validate expectation for a tesnet. Extract Stats or Metrics.
 - [ ] Persist raw outputs from the tests in google storage, so we can analyze results in some other time. Write a script to do so.

## Ideas for Test Scenarios

 * Testnet with 20 nodes. Introduce errors into the infrastructure (pumba/chaoskube) and introduce malicious nodes.
 * Testnet with 100 nodes. Introduce errors into the infrastructure (pumba/chaoskube) and introduce malicious nodes.
 * Testnet with a long history (lots of blocks). Use a small blocktime (1 sec?) so we can accelerate block production. We intend to see here what happens when the chain ages. 
 * Testnet with Short Epochs (Lot of elections)
 * Testnet with Long Epochs. What happens when querying historical information during one epoch. (eg. Misssing Trie node)
 * High Tx volume (saturate txpool)

## Other ideas (need to review)

 * Then we are also seeing occasional “sidechain reorg” and bad block messages which are worrying.
* e.g. running out of gas cos too many registered validators (Increase validator Size)
* Spam with governance proposals
* Number of transactions near the block gas limit in a range of currencies
* Consensus problems cos of a variety of proxy setups, latency, and peering issues.   Can we repro them by adding and removing nodes to the network continually?

## Notes on HOW TO TEST

* Create artificial errors:
   * Kill Containers (chaoskube)
   * Introduce Network Latency (pumba)
   * Byzantine Geth Nodes
* [Example of Test Configuration](https://github.com/celo-org/celo-monorepo/blob/timmoreton/ibftfaultytest/.env.ibftfaultytest#L82)
* To run pumba: `celotool deploy initial pumba -e …`
* [ChaosKube Helm Chart](https://github.com/helm/charts/blob/master/stable/chaoskube/README.md)
* don’t use preemptive machines
* One new envfile for test (don’t resuse them). Simpler to then query logs; since env file name == k8s.namespace
* `celotool.. destoy` doens’t kill k8s cluster, that has to be done manually.
* Create a new k8s cluster (or many) for tests (configured on the env file)
* Some things to try on tests:
	* kill & restart nodes
	* start w/ 20 and then w/100 nodes
	* test w/ proxies

**Comment by jcortejoso** [comment]
Chaos Testing Scenarios
------------------------

Common Setup:
 - 20 Validators
 - 15 proxies
 - Geth 1.9
 - Contracts and load test nodes deployed in the network
 - BlockTime 1 sec
 - Epoch 1000 blocks

1. Restart 1 validator pod (without cleaning roundstate)
  + Some block time (1/20) increases (~x5)
  + Showing different errors after it (e.g.: `Ignore preprepare message from non-proposer`)
  + Reconnects after epoch

2. Restart 1 validator pod (cleaning roundstate)
  + Some block time (1/20) increases (~x5)
  + After restarting the validator -> error `Failed to set randomness for proposer selection`
  + Validator starts proposing blocks after epoch

3. Restart 1 proxy pod (cleaning roundstate)
  + Validator associated with proxy stop proposing blocks
  + After proxy starts again (~2 minutes), the validator starts proposing new blocks again

4. Restart not a quorum (1/3 - 1) validators (without cleaning roundstate)
  + Remaining validators takes longer to validate new blocks
  + Restarted validators show `Ignore preprepare message from non-proposer`
  + After epoch block, the restarted validators start mining new blocks and the networks recover the blockstime speed.

5. Restart not a quorum (1/3 - 1) validators (cleaning roundstate)
  + Remaining validators takes longer to validate new blocks
  + Restarted validators show `Failed to set randomness for proposer selection`
  + After epoch block, the restarted validators start mining new blocks and the networks recover the blockstime speed.

6. Restart a quorum (1/3 + 1) validators (without cleaning roundstate)
  + No new blocks are mined afterwards.
  + After starting again, network state is unstable. New blocks are validated with a very high blocktime.
  + Recovering the network -> Restarting all (or a quorum) of the validators at the same time removing the roundstate folder

7. Restart a quorum (1/3 + 1) validators (cleaning roundstate)
  + No new blocks are mined afterwards.
  + The restarted nodes cannot validate/sign blocks -> The network cannot validate new blocks
  + Recovering the network -> Restarting all (or a quorum) of the validators at the same time removing the roundstate folder

8. Killing all the validators at the same time
  + The blocks start mining as soon as they are restarted

9. Killing all proxies at the same time
  + The blocks start mining as soon as they are restarted

10. Isolating validators (network partition)
  + After recovering connection the nodes are able to join the validation process (do not need to wait to epoch)

* With Byzantine nodes (faulty mode 1) the results are analogue to stopping the nodes.
