### ISSUE TITLE
Accelerated integration network deployed nightly with end to end tests

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#2642]
Integration environment. Things to do:

- [ ] Configure CI to deploy the master artifacts daily
- [x] Deploy automatically the tesnet
- [x] Deploy automatically the contracts
- [x] Deploy blockscout
- [x] Deploy celostats
- [x] Deploy oracle
- [ ] Deploy leaderboard
- [ ] Deploy ...
- [ ] Run E2E tests
- [ ] Submit results (slack/email/...)

Questions:
- Resetting/clean network or upgrading the contracts?
- VM testnet? K8s testnet? Both? Configurable?
