### ISSUE TITLE
Users SBAT reference protocol economic key metrics (back-end)

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#2665]
The backend should be able to fetch the following key metrics:

- [x] As a user I would like to view the historic data of currentGoldBucket and currentStableBucket
- [x] As a user I would like to view the amounts of cUSD and cGLD traded in this event and get also a view on the price (i.e. the ratio of those amounts)
- [ ] As a user I would like to view the historic data of the reserve ratio
- [x] As a user I would like to view the historic data of total cUSD paid to validators
- [x] As a user I would like to view the historic data of the yield payments
- [x] As a user I would like to have a consolidated view of the historic epoch rewards left vs rewards target

Preconditions to implement the above use cases are:

- [X] The architecture to put in place should be documented
- [X] The solution should be able to ingest information generated from Smart Contract events
- [x] The solution should be able to ingest information via direct calls to public methods or views of Smart Contracts

**Comment by aaitor** [comment]
The backend necessary to provide the requested metrics is available here:
https://github.com/celo-org/celo-monitoring

It was tested connecting to `baklava`. It is ingesting all the events/views information requested but the **reserve ratio** metric. The method necessary is not deployed yet in `baklava` network. 
In any case the configuration required to get that information is configured in the project, so as soon as the method is available the information will be ingested.
