### ISSUE TITLE
Celostats beta UI: sufficient and correct info for mainnet

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#2687]
- [x] Fix errors in Frontend	(see retro + feedback)
- [x] Fix bug with displaying pending transactions
- [x] Fix bug with displaying transactions in last block
- [x] Fix displaying wrong node accounts, seems related to id handling: https://github.com/celo-org/celo-monorepo/issues/2549
- [x] optimize the net code of celostats so we use less bandwidth. It is done but needs to be adapted in the new frontend because it is breaking from the client side: https://github.com/celo-org/celostats-server/pull/4
- [x] Evaluate geth 1.9 delta with celostats
- [x] ECDSA & BLS Key info into celostats
- [x] Operating: Celostats refactor and new frontend #2911
- [ ] ~E2E Integration tests~ issue is tracked here: #3024

**Comment by H34D** [comment]
closed, other open issue is tracked here: https://github.com/celo-org/celo-monorepo/issues/3024
