### ISSUE TITLE
Validator Explorer MVP: Figma design in web page

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#2688]
- [x] Add endpoints in blockscout for retrieving vote info
- [x] Launch Validator UI as part of web site for baklava phase 4
- [x] Design and add attestation information
- [x] Improve Page loading experience
