### ISSUE TITLE
Blockscout upstream and necessary API extensions:

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#2690]
- [x] Additional data about groups: total active votes, number of members
- [x] Network parameters: number of registered validators, total locked gold, min and max number of elected validators
- [x] Information about voter rewards for group: number of active votes, actual reward
- [x] Fix existing issues & upstream sync
- [x] Expose graphql API endpoints for the above

**Comment by mrsmkl** [comment]
Things that have to to added to DB
* Additional data about groups: total active votes, number of members
* Network parameters: number of registered validators, total locked gold, min and max number of elected validators
* Information about voter rewards for group: number of active votes, actual reward

Then we need a GraphQL API for all that.

**Comment by mrsmkl** [comment]
Most of these should be done in PR https://github.com/celo-org/blockscout/pull/82
