### ISSUE TITLE
Protocol economics monitoring tool prototype

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#2703]
- [ ] Provide a backend prototype to track and monitor public variables and events from Celo-blockchain (architecture that can extend to other data sources than geth)
- [ ] As a user I would like to view the historic data of currentGoldBucket and currentStableBucket 
- [ ] As a user I would like to view the amounts of cUSD and cGLD traded in this event and get also a view on the price (i.e. the ratio of those amounts)
- [ ] As a user I would like to view the historic data of the reserve ratio
- [ ] As a user I would like to view the historic data of total cUSD paid to validators
- [ ] As a user I would like to view the historic data of the yield payments
- [ ] As a user I would like to have a consolidated view of the historic epoch rewards left vs rewards target

**Comment by diminator** [comment]
close in favor of #2665
