### ISSUE TITLE
Celostats C Labs Engineer requirements

### ISSUE THREAD

**Issue by H34D** [celo-org/celo-monorepo#2783]
- [ ] Celostats C Labs Engineer requirements: I’m a developer #2739
- [ ] Celostats C Labs Engineer requirements: I’m a node operator #2738
- [ ] Celostats C Labs Engineer requirements: How busy/congested is the network? #2736
- [ ] Celostats C Labs Engineer requirements: Is there obviously a problem with any particular node? #2735
- [ ] Celostats C Labs Engineer requirements: is the network working #2734
