### ISSUE TITLE
Users SBAT reference protocol economic additional key metrics (backend)

### ISSUE THREAD

**Issue by aaitor** [celo-org/celo-monorepo#2826]
### Expected Behavior

The backend should be able to fetch the following key metrics:

- [x] As a user I would like to view the historic data of the median rate of the StableToken
- [x] As a user I would like to view the total amount of cGLD in the reserve
- [x] As a user I would like to view the historic data of total cUSD paid to groups
- [x] As a user I would like to view the historic data of the yield percentage
- [x] As a user I would like to view the historic data of the epoch rewards multiplier

In addition to this, it would be necessary to:

- [X] Document the solution architecture
- [X] Provide the possibility of replay previous blocks
- [X] Fix some data type issues

**Comment by aaitor** [comment]
The Celo Monitoring design document can be found here: https://docs.google.com/document/d/1Kg6x-loGv7hWlRnN1mUVAKmtv4CiIjkne52eRt5TfH8/edit#
