### ISSUE TITLE
Protocol Economics Monitor Dashboard with Celo Stack

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#3070]
### Commit
- [x] access public views with exporter
- [x] make sure all events are being reported
- [x] export relevant data to bigquery
- [ ] create Reserve dashboard in datastudio
- [ ] create PoS dashboard in datastudio

### Stretch
- [x] failover strategy with replay and catchup
