### ISSUE TITLE
Celostats upgrade and load tests

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#3071]
- [x] Upgrade & swap frontend 
- [x] Design signature profile graph (total and per node) + reconcile with block proposer graph
- [x] Fix loading
- [ ] ~Load testing on websockets 300 connections~ will be tracked here: https://github.com/celo-org/celo-monorepo/issues/3024

**Comment by H34D** [comment]
> * Load testing on websockets 300 connections

this is still open as of today

**Comment by H34D** [comment]
closed in favour of https://github.com/celo-org/celo-monorepo/issues/3024
