### ISSUE TITLE
Internal audit of governance inc tooling+hotfixes

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#3080]
Work in pairs, or divide-and-conquer.

Goal is to produce a brief document we can walk-through as a group that covers the following: 

- [ ] How does this work?
- [ ] What are the dependencies? 
- [ ] What design docs or specs cover this feature? Any gaps? Is the spec wrong, or the implementation?
- [ ] Are there areas missing unit tests? 
- [ ] What e2e tests cover this? What could be added?
- [ ] Are inputs validated?
- [ ] Are parameters and constants set sensibly?
- [ ] If we discover a serious issue, how many hrs to a full fix inc data recovery?
- [ ] What is the path for upgrading or changing this feature (e.g governance, backwards-compatible validator upgrade, hard fork, ..)?  Does this difficulty match the quality and completeness?
- [ ] How could this be attacked?
- [ ] Are the user docs correct and complete? Links to code?

Share document, then comment on the doc, then let's have the walkthrough meeting before end of Sprint.

**Comment by H34D** [comment]
In the governance process is written that contract upgrades can be proposed by every actor in the system known or unknown.

`Any user may submit a “Proposal” to the Governance smart contract, along with a small deposit of Celo Gold. This deposit is required to avoid spam proposals, and is refunded to the proposer if the community decides the proposal is worthy of voting on.`

How to detect malicious actors / malicious code in this process? Once the code has been proposed it will be stored as bytecode. How to make sure (i.e. the code changes when upgrading smart contracts) being voted on is not harmful?

There is a spam protection in place (with Celo gold at stake). Potential other mechanism to rule out bad code could be some sort of attestation or testimony by the community or other voters. To enable this the voters need details about the changes, like actual code changes or a delta of the code before and after.
