### ISSUE TITLE
Internal audit of Proof of Stake

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#3082]
Work in pairs, or divide-and-conquer.

Goal is to produce a brief document we can walk-through as a group that covers the following: 

- [ ] How does this work?
- [ ] What are the dependencies? 
- [ ] What design docs or specs cover this feature? Any gaps? Is the spec wrong, or the implementation?
- [ ] Are there areas missing unit tests? 
- [ ] What e2e tests cover this? What could be added?
- [ ] Are inputs validated?
- [ ] Are parameters and constants set sensibly?
- [ ] If we discover a serious issue, how many hrs to a full fix inc data recovery?
- [ ] What is the path for upgrading or changing this feature (e.g governance, backwards-compatible validator upgrade, hard fork, ..)?  Does this difficulty match the quality and completeness?
- [ ] How could this be attacked?
- [ ] Are the user docs correct and complete? Links to code?

Share document, then comment on the doc, then let's have the walkthrough meeting before end of Sprint.

**Comment by H34D** [comment]
https://docs.celo.org/celo-codebase/protocol/proof-of-stake

**Comment by H34D** [comment]
My ToDo's

- [x] pos.go
- [ ] validators.sol
- [ ] accounts.sol

**Comment by jose-compu** [comment]
First version of report covering some of the most important modules Node **pos.sol**, contract **Election.sol**, contract **LockedGold.sol**. https://docs.google.com/document/d/1SHaxaeretavJIk-mC96SA83LoKOxG_n2gBpAIgAIT9k/edit?userstoinvite=a%40celo.org&ts=5e7b8c46&actionButton=1#heading=h.yx6vxgosxfso

**Comment by jose-compu** [comment]
Need to double-check if we want to fix High priority items now before mainnet or not. Also confirm if we want to open issues for Medium and Low priority items.

**Comment by H34D** [comment]
> My ToDo's
> 
> * [x]  pos.go
> * [ ]  validators.sol
> * [ ]  accounts.sol

this is the current status quo
