### ISSUE TITLE
Internal audit of transaction changes

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#3084]
Work in pairs, or divide-and-conquer.

Goal is to produce a brief document we can walk-through as a group that covers the following: 

- [x] How does this work?
- [x] What are the dependencies? 
- [x] What design docs or specs cover this feature? Any gaps? Is the spec wrong, or the implementation?
- [x] Are there areas missing unit tests? 
- [x] What e2e tests cover this? What could be added?
- [x] Are inputs validated?
- [x] Are parameters and constants set sensibly?
- [x] If we discover a serious issue, how many hrs to a full fix inc data recovery?
- [x] What is the path for upgrading or changing this feature (e.g governance, backwards-compatible validator upgrade, hard fork, ..)?  Does this difficulty match the quality and completeness?
- [x] How could this be attacked?
- [x] Are the user docs correct and complete? Links to code?

Share document, then comment on the doc, then let's have the walkthrough meeting before end of Sprint.

**Comment by timmoreton** [comment]
Cover implementation of these three bullet points:
https://docs.celo.org/v/master/celo-codebase/protocol/transactions

Search for "gpm", "GatewayFee", and "FeeCurrency" in celo-blockchain - I can provide more pointers too

**Comment by jeanregisser** [comment]
Thanks @timmoreton, I'll start from this!

**Comment by timmoreton** [comment]
https://docs.google.com/document/d/1WuRKVYaBIgldUpthG5MVKCJ9PHj_D3eSUvNi1jEFOuA/edit#heading=h.z1po193c4l94
