### ISSUE TITLE
Blockscout GraphQL API extensions

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#3086]
### URL Attestations
- [x] complete flow for URL attestations, see #2787
- [x] crawl attestations and populate in blockscout-postgres
- [x] expose attestations to graphql API
- [x] integration of complexity filter for graphql nested queries 

### Phone Number Privacy 
- [x] stake/balance over time calculation, info to be provided by @kobigurk

**Comment by aaitor** [comment]
Blockscout PR: https://github.com/celo-org/blockscout/pull/90

The follwoing GraphQL query can be integrated in the frontend to retrieve the domain claims:
```
{celoClaims(hash: "0x908CbC72876f3638eD8C5A5c9f57D6Fba7D4743d") { type, address, element }}
```

This should return a list of the domain claims:
```
{
  "data": {
    "celoClaims": [
      {
        "address": "0x908cbc72876f3638ed8c5a5c9f57d6fba7d4743d",
        "element": "example.com",
        "type": "domain"
      }
    ]
  }
}
```

**Comment by kobigurk** [comment]
@jmrossy @aslawson @codyborn can you take a look?

**Comment by jmrossy** [comment]
@diminator @aaitor We won't be needing a stake/balance over time calculation from blockscout for phone number privacy anymore. We'll instead be using the tx count provided by web3. 

So you can check off that box for now and we'll circle back if the requirements change in the future :)
