### ISSUE TITLE
Blockscout Simple Load testing

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#3088]
- [x] load test GraphQL API with >= 50 connections
- [x] test complex GraphQL queries that could brake the instance
- [x] load test the web frontend

**Comment by aaitor** [comment]
After some analysis of the integration of Absinthe into Blockscout, some details:

* Blockscout includes an initial integration of `max_complexity` filter of Absinthe
https://hexdocs.pm/absinthe/complexity-analysis.html

* It uses a `max_complexity` of 200 that can be found in  `lib/block_scout_web/router.ex`

* The filter by complexity needs to be integrated in each Graphql query, currently is only included in:
  - Gets addresses by address hash.
  - Gets token transfers by token contract address hash

My suggestion on that would be:

- Identify potential Graphql queries to protect 
- Implement & test the `max_complexity` filter in each of those
- Evaluate if we need different thresholds per query or the general threshold of `200` is good enough

**Comment by aaitor** [comment]
Blockscout PR: https://github.com/celo-org/blockscout/pull/93

**Comment by aaitor** [comment]
Graphql api test scenario:

- Running in a server with 8GB RAM and 1vCPU
- Using alfajores data
- 50 virtual users * 22 minutes

```
All virtual users finished
Summary report @ 14:24:00(+0200) 2020-04-07
  Scenarios launched:  500
  Scenarios completed: 500
  Requests completed:  111500
  Mean response/sec: 82.3
  Response time (msec):
    min: 51.9
    max: 45484.1
    median: 3452.7
    p95: 19940.1
    p99: 32707.5
  Scenario counts:
    GraphQL Query load test: 500 (100%)
  Codes:
    200: 111500

Done in 1356.75s.
```

Running that scenario we didn't find any error code

**Comment by aaitor** [comment]
Testing with Jmeter the frontend I found some errors with more than 6/7 concurrent users:

```
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.jmeter.protocol.http.sampler.hc.LazyLayeredConnectionSocketFactory.connectSocket(LazyLayeredConnectionSocketFactory.java:92)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl$JMeterDefaultHttpClientConnectionOperator.connect(HTTPHC4Impl.java:326)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:850)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:561)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:67)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1282)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1271)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

These errors doesn't look specific of blockscout code but of the load balancing of the application. Further investigation is required.

**Comment by aaitor** [comment]
Load tested the UI using JMeter with 25 concurrent users. No errors found.
![image](https://user-images.githubusercontent.com/1726644/79242389-8e7bb700-7e74-11ea-8d17-13ef9f0bb39f.png)
