### ISSUE TITLE
New design system

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#3645]
https://www.figma.com/file/zt7aTQ5wuXycIwxq5oAmF9/Wallet--Refresh?node-id=2930%3A0

- [ ] Design Kit
  - [x] colors, fonts, Buttons (#3691)
    - [x] Button
  - [x] Avatars
  - [x] Loading Spinner
  - [x] Inputs fields
    - [x] Switch
  - [x] Guide (aka Education)
  - [x] Top bar elements
     - [x] CancelButton #3772
     - [x] TopBarButton #3772
     - [x] BackButton  #3803
     - [x] Central header with Subheader #3803
  - [x] Banners  (AKA Alerts in the code)
  - [ ] Toast
  - [x] Messaging #3840
  - [x] Dialogs #3863
  - [x] Card in #3840 (A View with shadow)
  - [x] Custom Keyboard https://github.com/celo-org/celo-monorepo/pull/3879
  - [x] Lists 
     - [x] Transactions / People #3815
     - [x] Settings
     - [x] Receipt Layout (@i1skn is working on it as a part of https://github.com/celo-org/celo-monorepo/pull/3764, can extract it earlier if needed)
     - [x] On Celo Gold tab and Cash In/Out (it should be similar to one in Gold Screen - https://github.com/celo-org/celo-monorepo/pull/3764)
- [ ] Account Key (#3660)
  - [x] Core Flow
  - [x] Guide
  - [x]  back button hide when no words selected
  - [x]  Modal that pops up when you go to cancel
   - [ ] The Screenshot Prevention.
- [x] Gold (#3659)
- [x] Home
  - [x] Home Screen #3815
  - [x] Notifications #3840
  - [x] Transactions drilldowns #3910
  - [x] QR Scanning
  - [x] Send flow 1st part #3895 
  - [x] Send flow 2nd part #3904
  - [x] Secure Send flow #3904 
  - [x] Request flow #3953
  - [x] Invite flow #3953
- [x] Cash In (#3848)
- [x] Settings
- [x] Help (https://github.com/celo-org/celo-monorepo/pull/4274)
- [ ] ~~Invite (deprecated for now)~~
- [ ] Onboarding flow
- [x] Navigation
   - [x] react-navigation v5 #3799
   - [x] drawer menu #3894
- [x] Pin code screen

**Comment by aaronmgdr** [comment]
This is a good start, we should just be aware that there will be things in progress and that we might complete part of these

**Comment by i1skn** [comment]
I've detailed some bullets and added `who is working on it right now` notices.

**Comment by aaronmgdr** [comment]
Are we ready to close this ? @jeanregisser
