### ISSUE TITLE
Refactor "getting started" docs to improve security and reliability of the resulting setup

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-monorepo#3972]
- [ ] Integrate IPC into docs and tooling as the recommended RPC mode
- [ ] Integrate the use of config files into documentation for simplicity and reliability
- [ ] Integrate best practices for avoiding chain data corruption into documentation
