### ISSUE TITLE
Deliver PoC for Grameen Project (based on World Bank)

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#3978]
Pre-production release 
- [x] Assemble components into pages
- [x] Style pages with Grameen branding
- [x] Host as service
- [ ] Provide celocli tooling
- [ ] Associate addresses with private labels for a project with CSV
- [ ] Better understand their Identity system and integrate permissions
- [x] Timelapse view on Sankey
- [ ] CSV export
- [ ] view transactions for a recipient (part of filter?)
- [x] project level analytics (stretch)
- [x] multiple destination addresses (stretch)

Shared components
- [x] Transaction view
- [x] Sankey
- [x] SSO
- [x] Single transaction sender 
- [ ] entity view
- [ ] permissions (stretch)

Not in this PoC
- [x] no documents
- [x] no transaction sending

**Comment by diminator** [comment]
@nityas @pranaymohan it would be great if we have a better understanding of what's going to be the process for:

> Better understand the native Identity system and integrate permissions

Grameen has an identity system (potentially email, LDAP, ...). 
- Which one will be used for login into the dashboard?
- Which emails/accounts from grameen will have access? Does there need to be a whitelist?

> Associate addresses with private labels for a project with CSV

The addresses of the recipients are assumed to be coming from celo mobile wallet users in the Grameen ecosystem. 
- Which user will do the association? the main admin of the dashboard?
- How are these addresses known to this user?
- What is the process for uploading the CSV? do we extend this to the dashboard or the celocli?
- How are projects created? in the dashboard through a page or with a CLI? do we need wireframes?

> Provide celocli tooling for sending bulk transactions

Grameen Custodian should be able to use the celocli with appropriate keystore/private key to send bulk transactions given a list of addresses and amounts. 
- How is that list compiled?
- Where are the addresses registered? see above
- How do we envision the sender to use the celocli? (what computer, where are the keys stored, is there a backup, when to use the keys)

cc @eruizgar91 @H34D

**Comment by barbaraliau** [comment]
Done.
