### ISSUE TITLE
Deliver and integration Document Mgmt System for WB PoC

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#3979]
Set up data model in the backend and populate with mock information:
- [x] Projects
- [x] Transactions (following Celo Transaction Types)
- [x] Documents

Document upload flow
- [x] pick files or access camera (mobile)
- [x] hash files and sign + send as transfer comment
- [x] upload session to S3

Document View
- [x] endpoint for documents through amplify datastore and connect to frontend
- [x] document list and view permissions/roles per doc or project (stretch)
- [x] frontend components
