### ISSUE TITLE
Deliver and integration Identity + Wallet for WB PoC

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#3980]
Create Identity flow
- [x] Single Sign on with email (WB, Grameen)
- [x] Create mapping between app account/project and celo wallet account or "tag addresses" (WB, Grameen)

Permissioning
- [x] Store roles / permissions in datastore (WB stretch, not grameen)
- [x] Show limited sankey diagram (WB mock, not grameen)
- [x] Show subset of projects, transactions & docs (WB stretch, not grameen)

Create minimal transaction signing flow (WB, stretch? or mock, not grameen)
- [x] Compose transaction with comment
- [x] Sign with KMS
- [x] Publish on network
- [x] Await confirmation and update
- [x] Figure out gas fees
