### ISSUE TITLE
Deliver and integration of Transactions + Sankey Diagram for WB PoC

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-monorepo#3981]
Provide backend and frontend state store
- [x] Index celo and provide graphql endpoint  [WB, Grameen]
- [x] Read Transactions from Celo network [WB, Grameen]
(Transactions list and detail endpoint, assume filter/project addresses are known)
- [x] Prepare data to populate sankey diagram [WB, Grameen]

Create frontend components
- [x] Sankey diagram [WB, Grameen]
- [x] List & detail view on transactions [WB, Grameen]
- [x] Filter and search component [WB, Grameen]
- [x] Hover view on sankey [WB, Grameen]
- [x] Create Transaction [defer to mocks for WB, not for Grameen]
