### ISSUE TITLE
Automated release process

### ISSUE THREAD

**Issue by gastonponti** [celo-org/celo-monorepo#3992]
- [ ] Research Github Packages if it could be useful
 - [ ] Create a script to check (with a dry run) and publish a new package
 - [x] Utils published
 - [x] ContractKit published (multiple packages done?)
 - [x] Cli published
 - [ ] ci workflow to publish it (?)

**Comment by aslawson** [comment]
closing -- duplicate
