### ISSUE TITLE
Define and divide the contractKit into multiple modules

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#4001]
- [ ] SDK module as consumer and configuration layer of other modules #4002 
- [ ] Provider module as web3/celo provider wrapper #3993
- [x] Instrument module bundle sizes #4445
- [ ] Contracts module as typechain/abi wrapper #4450
- [x] Wallets module
