### ISSUE TITLE
[Wallet] Grameen pilot wallet support

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4400]
### Expected Behavior

Confirm that all wallet-related needs for Grameen pilot are in wallet:
- [ ] Philippine peso (PHP)
- [ ] Tagalog language
- [ ] Locale gives correct country code
- [ ] Update to terms if needed

Can be tested with ecosystem leads in the Philippines. 

### Current Behavior

PHP currency available in app. Tagalog language not yet added. Unconfirmed whether locale gives correct country code.

**Comment by nityas** [comment]
closing out- older issue
