### ISSUE TITLE
Finalize the automation of the smart contract upgrade process

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#4426]
- [x] Finalize #3893 and #4277 .
- [x] Script to verify a contracts directory has contracts that are deployed on-chain (deployed bytecode, modulo metadata, matches) (#4996)
- [x] Read version numbers from contracts (#4523)
- [x] Use the above in CI to verify changes against `master`. (#4523)
- [x] Create and document script that is easily usable externally for due diligence of governance proposals (#5038)
- [x] Script to generate governance proposal data and deployment transactions from diff of contracts' directories. (#4706)

**Comment by asaj** [comment]
Thinking about sequencing here, the following things need to happen before we can kick off the first contract upgrade:

- Finalize automated tooling
    - Check build directory matches deployed contracts (@m-chrzan)
    - Check implied version deltas match actual (@asaj)
    - CI integration (???)
    - Automate governance proposal creation (???)
- Finalize desired contract changes
    - DowntimeSlasher (@gastonponti)
    - Exchange (https://github.com/celo-org/celo-proposals/pull/26) (???)
    - Version numbers (@asaj)
- Complete third party audit(s)

Anything else?
