### ISSUE TITLE
Conduct contract release 1

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#4812]
This issue is tracking Celo's first smart contract upgrade release. While executing upon this release according to the process laid out in https://docs.celo.org/community/release-process/smart-contracts, we are simultaneously going to improve it as we go and reference those changes here as well

Process Checklist:

- [x] [Merge all changes that should go into release 1](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-691184631)
- [x] [Cut release branch and submit branch to auditors](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-691186072)
- [x] Receive Audit report
- [x] Address issues found in audit
- [x] Submit audit fixes to auditors @emaG3m @yorhodes 
- [x] [Receive final audit report](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-706883667)
- [x] Write up release/governance proposal notes @alecps 
- [x] [Make release on Github and add @alecps's release notes draft](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-699127362) @nambrot 
- [x] [(Sep 29) Propose GasLimit increase on Baklava](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-700888483) @alecps 
- [x] [(Oct 6) Propose GasLimit increase on Alfajores](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-704501034) @aslawson @emaG3m 
- [x] [(Oct 13) Propose GasLimit increase on Mainnet](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-708021473) @aslawson 
- [x] Deploy contracts on Baklava @yorhodes 
- [x] Verify Deploy on Baklava (i.e. test downtime slasher) @yorhodes 
- [x] Propose contract upgrade on Baklava 
- [x] Deploy contracts on Alfajores 
- [x] Propose contract upgrade on Alfajores
- [x] Verify Deploy on Alfajores (i.e. test downtime slasher)
- [x] Deploy contracts on Mainnet
- [x] Propose contract upgrade on Mainnet

Blockers:
- [x] [Testing that raising the block gas limit is safe](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-696272192)

To-Dos:
- [x] Review [@m-chrzan's verify-bytecode](https://github.com/celo-org/celo-monorepo/pull/4996/files) PR @emaG3m @yorhodes 
- [x] [Update docs with an overview of deployment/verification tooling](https://github.com/celo-org/celo-monorepo/issues/5038) @yorhodes 
- [x] [Script to verify currently deployed contracts bytecode](https://github.com/celo-org/celo-monorepo/issues/5082) @yorhodes 
- [x] [Script to verify proposal is well formed and matched commit](https://github.com/celo-org/celo-monorepo/issues/5084) @yorhodes 
- [x] [Enumerate relevant PRs for release notes](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-691184631)
- [x] Setup comms plan with community @cla-bel 
- [x] [Update promotion process with comms action items](https://github.com/celo-org/celo-monorepo/pull/5200) @cla-bel
- [x] Update release process docs @emaG3m 
- [x] [Add branching process to docs](https://github.com/celo-org/celo-monorepo/pull/5212) @nambrot 
- [x] [Write CGP for GasLimit Increase](https://github.com/celo-org/celo-proposals/pull/46) @nambrot 
- [x] [Write announcement context post in time for baklava gasLimit increase proposal](https://forum.celo.org/t/governance-proposals-to-make-the-protocol-safe-and-easy-to-upgrade/615) @cla-bel 
- [x] Fix master CI version check @emaG3m 
- [x] [Update docs that accomodates right reference for CI version check](https://github.com/celo-org/celo-monorepo/pull/5269) @emaG3m 
- [x] Update docs with a process to handle initialize data
- [x] Remove release 1 specific tooling after release 1
- [x] Update docs with process for cutting release branch and updating reference of CI checks for master @emaG3m 
- [x] Properly tag what's currently deployed on the networks @nambrot 
- [x] [Merge release branch back into master](https://github.com/celo-org/celo-monorepo/pull/5338) @nambrot 
- [x] give auditors next release commit
- [x] [verify-bytecodes should output positive messaging](https://github.com/celo-org/celo-monorepo/pull/5398) @m-chrzan 
- [x] verify proposal should check initialize data
- [x] [Suppress script output in verification scripts](https://github.com/celo-org/celo-monorepo/pull/5418) @nambrot 
- [x] Always use canonical build version of scripts of user commit @m-chrzan  
- [x] [Add `--dryrun` to make-release script and reconcile build args](https://github.com/celo-org/celo-monorepo/pull/5347) @nambrot easy
- [x] [Add `SlasherUtil`/`UsingPrecompiles` hack since it added `getVersionNumber`](https://github.com/celo-org/celo-monorepo/pull/5346) @yorhodes 
- [x] [`getVersionNumber` only on proxied contracts](https://github.com/celo-org/celo-monorepo/pull/5340)
- [x] All proxied contracts have `getVersionNumber`
- [x] `make-release` only releases contracts with proxies 
- [x] Have logic to determine which contracts should actually be deployed (fix Regex exclusion) @yorhodes 
- [x] Remove `MetaTransactionWallet` from check version @yorhodes 
- [x] [Write CGP13](https://github.com/celo-org/celo-proposals/pull/53) @nambrot 
- [x] [Write Incident Response and recommend scientific notation in CLI governance:propose/view](https://docs.google.com/document/d/11oKD073WIp4nd87_I_lt-RIlWa0gscpM5_MhqNoi-Ng/edit#heading=h.88321r39zajd) @nambrot 
- [x] [Remove `getVersionNumber` from wrong files](https://github.com/celo-org/celo-monorepo/pull/5340) @nambrot 
- [x] Verify that txs in a proposal are actually valid
- [x] Fix CLI decoding of governance transactions (currently, getting `Contract` instead of `ContractProxy` when decoding a contract upgrade governance proposal, which breaks `verify-release`)
- [x] Publish CLI with `--jsonProposals` option to `governance:show`
- [x] `verify-release` should check Proxy bytecodes and owners
- [x] Call Proxy initializers via Governance in `make-release`, check that new Proxies have empty bytecode in `verify-release`
- [x] Allow truffle overrides in `make-release`
- [x] Update gasLimit in Truffle config given CGP 12

**Comment by nambrot** [comment]
Meaningful PRs that went in this release:
- Downtime Slasher https://github.com/celo-org/celo-monorepo/pull/3806
- Wiggle Room for LockedGold requirements https://github.com/celo-org/celo-monorepo/pull/4461
- Allow signer to withdraw attestation fees https://github.com/celo-org/celo-monorepo/pull/4298
- Add sell/buy functions for Exchange.sol https://github.com/celo-org/celo-monorepo/pull/4580
- Allow the transferring of attestations https://github.com/celo-org/celo-monorepo/pull/4583

**Comment by nambrot** [comment]
The commit that was submitted to OpenZeppelin was https://github.com/celo-org/celo-monorepo/tree/b2f0a58fcc7667d41585123aae5b24c47aa894f6 and the release branch is [oz-prerelease](https://github.com/celo-org/celo-monorepo/tree/oz-prerelease)

**Comment by alecps** [comment]
Release Notes draft in progress here https://docs.google.com/document/d/1vmZCKJRM9WO4VYinKEb5q4QetXjNzYFxq0AvPy_t8pA/edit Please add any improvements!

**Comment by nambrot** [comment]
@pranaymohan confirmed that increasing the block gas limit to 13M is safe to do with the current blockchain version on Mainnet. Thanks @jcortejoso @kevjue @vslavich @mcortesi!

**Comment by nambrot** [comment]
CGP for the block gas limit increase proposal https://github.com/celo-org/celo-proposals/pull/46

**Comment by nambrot** [comment]
Created the branch [`release/contracts/1`](https://github.com/celo-org/celo-monorepo/tree/release/contracts/1) with tag [`celo-contracts-v1.rc1`](https://github.com/celo-org/celo-monorepo/releases/tag/contracts-v1.rc1) and made a prerelease release at https://github.com/celo-org/celo-monorepo/releases/tag/celo-contracts-v1.rc1

**Comment by aslawson** [comment]
Baklava Gas Limit Increase has been proposed as `proposal 4`.
`celocli governance:view --proposalID 4 --node https://baklava-forno.celo-testnet.org`

It will enter into approval stage tomorrow ~10:40AM PDT.  Baklava just needs 1 approver.

It will then enter the voting stage Thursday.

**Comment by nambrot** [comment]
Block Gas Limit Increase Proposal on Baklava is approved 

```
celocli governance:view --proposalID 4 --node https://baklava-forno.celo-testnet.org
Running Checks:
   ✔  4 is an existing proposal 
proposal: 
  0: 
    contract: BlockchainParameters
    function: setBlockGasLimit
    args: 
      0: 130000000
    params: 
      gasLimit: 130000000
    value: 0
metadata: 
  proposer: 0xF3EB910DA09B8AF348E0E5B6636da442cFa79239
  deposit: 100000000000000000000 (~100 10^18)
  timestamp: 1601494320 
  transactionCount: 1
  descriptionURL: https://github.com/celo-org/celo-proposals/blob/master/CGPs/0011.md
stage: Approval
upvotes: 0 
votes: 
  Yes: 0 
  No: 0 
  Abstain: 0 
passing: false
requirements: 
  participation: 0.0143430905876 
  agreement: 80%
isApproved: true
isProposalPassing: false
secondsUntilStages: 
  referendum: 12863 
  execution: 99263 
  expiration: 704063 
```

**Comment by nambrot** [comment]
Baklava GasLimit Proposal is executed, blocks are stable!

```
celocli governance:execute --proposalID 4 --from 0xfcf982bb4015852e706100b14e21f947a5bb718e
Running Checks:
   ✔  4 is an existing proposal 
   ✔  4 is in stage Execution 
   ✔  Proposal 4 is passing corresponding constitutional quorum 
SendTransaction: executeTx
txHash: 0x552d82ceeeafce060c5b28557c513af60f957280aebc4853ad0e7a99a0a2c315
Sending Transaction: executeTx... done
ProposalExecuted:
proposalId: 4
```

**Comment by alecps** [comment]
The Block Gas Limit update has been proposed on Alfajores with proposalID 1 
```
proposal: 
  0: 
    contract: BlockchainParameters
    function: setBlockGasLimit
    args: 
      0: 130000000
    params: 
      gasLimit: 130000000
    value: 0
metadata: 
  proposer: 0xB10c80EB948057eDfb7D0eF9BAD319144efC8568
  deposit: 100000000000000000000 (~100 10^18)
  timestamp: 1602004704 
  transactionCount: 1
  descriptionURL: https://github.com/celo-org/celo-proposals/blob/master/CGPs/0011.md
stage: Queued
upvotes: 0 
votes: 
  Yes: 0 
  No: 0 
  Abstain: 0 
passing: false
requirements: 
  participation: 0.005 
  agreement: 80%
isApproved: false
isProposalPassing: false
secondsUntilStages: 
  referendum: 1509 
  execution: 5109 
  expiration: 91509 
```

**Comment by alecps** [comment]
The blockGasLimit proposal has been executed on alfajores

**Comment by yorhodes** [comment]
The release process documentation is up to date with the internal and community tooling.
https://docs.celo.org/community/release-process/smart-contracts#release-process

**Comment by abcoathup** [comment]
The cLabs team asked OpenZeppelin to review and audit the recent changes in the smart contracts from their protocol. 

We examined the code, and here we publish our findings in Phase 3.  👇
The relevant commits are specified in the report.
https://blog.openzeppelin.com/celo-contracts-audit

**Comment by nambrot** [comment]
Block GasLimit increase proposal is live on Mainnet, thanks @aslawson https://celo.stake.id/#/proposal/11

**Comment by nambrot** [comment]
Thanks @zviadm for noticing that our block gasLimit proposals had specified the wrong number for the increase (130M instead of 13M). This post will track the work needed to rectify that mistake:

- [x] Inform approvers of Mainnet multisig to not approve @nambrot 
- [x] Dequeue the current Mainnet Proposal 12 @aslawson 
- [x] Create forum post on this issue @YazzyYaz 
- [x] [Mark [CGP11] as REJECTED](https://github.com/celo-org/celo-proposals/pull/50) on https://github.com/celo-org/celo-proposals/blob/master/CGPs/0011.md
- [x] [Create new CGP12 that sets it to the right value](https://github.com/celo-org/celo-proposals/pull/51)
- [x] [Propose CGP12](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-708665098) on Baklava
- [x] [Propose CGP12 on Alfajores](https://github.com/celo-org/celo-monorepo/issues/4812#issuecomment-708667755)
- [ ] Propose CGP12 on Mainnet (pending success on Baklava/Alfajores)
- [ ] [Incident report and steps to improve](https://docs.google.com/document/d/11oKD073WIp4nd87_I_lt-RIlWa0gscpM5_MhqNoi-Ng/edit#)

**Comment by nambrot** [comment]
Baklava Proposal to set the gasLimit to 13M has been proposed 

```
celocli governance:view  --proposalID 5 --node https://baklava-forno.celo-testnet.org
Running Checks:
   ✔  5 is an existing proposal 
proposal: 
  0: 
    contract: BlockchainParameters
    function: setBlockGasLimit
    args: 
      0: 13000000
    params: 
      gasLimit: 13000000
    value: 0
metadata: 
  proposer: 0xfCf982bb4015852e706100B14E21f947a5Bb718E
  deposit: 101000000000000000000 (~101 10^18)
  timestamp: 1602710113 
  transactionCount: 1
  descriptionURL: https://github.com/celo-org/celo-proposals/pull/51
stage: Queued
upvotes: 0 
votes: 
  Yes: 0 
  No: 0 
  Abstain: 0 
passing: false
requirements: 
  participation: 0.1842132935244 
  agreement: 80%
isApproved: false
isProposalPassing: false
secondsUntilStages: 
  referendum: 14357 
  execution: 100757 
  expiration: 705557 
```

**Comment by nambrot** [comment]
Alfajores Proposal to set the gasLimit to 13M has been proposed 
```
celocli governance:view  --proposalID 2 --node https://alfajores-forno.celo-testnet.org
Running Checks:
   ✔  2 is an existing proposal 
proposal: 
  0: 
    contract: BlockchainParameters
    function: setBlockGasLimit
    args: 
      0: 13000000
    params: 
      gasLimit: 13000000
    value: 0
metadata: 
  proposer: 0x456f41406B32c45D59E539e4BBA3D7898c3584dA
  deposit: 101000000000000000000 (~101 10^18)
  timestamp: 1602710543 
  transactionCount: 1
  descriptionURL: https://github.com/celo-org/celo-proposals/pull/51
stage: Queued
upvotes: 0 
votes: 
  Yes: 0 
  No: 0 
  Abstain: 0 
passing: false
requirements: 
  participation: 0.013997244463 
  agreement: 80%
isApproved: false
isProposalPassing: false
secondsUntilStages: 
  referendum: 1774 
  execution: 5374 
  expiration: 91774 
```

**Comment by nambrot** [comment]
Alfajores Proposal to set the gasLimit to 13M has been executed

**Comment by nambrot** [comment]
Baklalva Proposal to set the gasLimit to 13M has been executed

**Comment by nambrot** [comment]
The block gas limit increase has been proposed on Mainnet

```
celocli governance:view  --proposalID 12 --node https://rc1-forno.celo-testnet.org
Running Checks:
   ✔  12 is an existing proposal 
proposal: 
  0: 
    contract: BlockchainParameters
    function: setBlockGasLimit
    args: 
      0: 13000000
    params: 
      gasLimit: 13000000
    value: 0
metadata: 
  proposer: 0xF3EB910DA09B8AF348E0E5B6636da442cFa79239
  deposit: 100000000000000000000 (~100 10^18)
  timestamp: 1603315388 
  transactionCount: 1
  descriptionURL: https://github.com/celo-org/celo-proposals/blob/master/CGPs/0012.md
stage: Approval
upvotes: 0 
votes: 
  Yes: 0 
  No: 0 
  Abstain: 0 
passing: false
requirements: 
  participation: 0.1807886970308 
  agreement: 80%
isApproved: false
isProposalPassing: false
secondsUntilStages: 
  referendum: 26131 
  execution: 458131 
  expiration: 717331 
```

**Comment by nambrot** [comment]
Baklava Contract Upgrade has been proposed 

Proposal was not executed since it contained a bug

**Comment by AlexBHarley** [comment]
Baklava contract upgrade has been proposed 

```
➜  protocol git:(master) ✗ celocli governance:show --proposalID 10

Running Checks:
   ✔  10 is an existing proposal
Outputting proposal JSON to upgrade_proposal.json
proposal:
  0:
    contract: AccountsProxy
    function: _setImplementation
    args:
      0: 0xf757feFA575bceA6Eba3fFB25723916F94858997
    params:
      implementation: 0xf757feFA575bceA6Eba3fFB25723916F94858997
    value: 0
  1:
    contract: AttestationsProxy
    function: _setImplementation
    args:
      0: 0x087bc230d256E5107C805c261817A1EF621C5046
    params:
      implementation: 0x087bc230d256E5107C805c261817A1EF621C5046
    value: 0
  2:
    contract: DoubleSigningSlasherProxy
    function: _setImplementation
    args:
      0: 0x8781541FAb84d7f83a670d057b5a75896947fE5d
    params:
      implementation: 0x8781541FAb84d7f83a670d057b5a75896947fE5d
    value: 0
  3:
    contract: Registry
    function: setAddressFor
    args:
      0: DowntimeSlasher
      1: 0xC743C9a58050a669ec4aff41D8A6C76f2264e206
    params:
      identifier: DowntimeSlasher
      addr: 0xC743C9a58050a669ec4aff41D8A6C76f2264e206
    value: 0
  4:
    contract: DowntimeSlasherProxy
    function: _setAndInitializeImplementation
    args:
      0: 0xf50E030d37D5d243b246D9cBe44Eff6144d8302A
      1: 0x4ec81af1000000000000000000000000000000000000000000000000000000000000ce100000000000000000000000000000000000000000000000056bc75e2d631000000000000000000000000000000000000000000000000000008ac7230489e8000000000000000000000000000000000000000000000000000000000000000021c0
    params:
      implementation: 0xf50E030d37D5d243b246D9cBe44Eff6144d8302A
      callbackData: 0x4ec81af1000000000000000000000000000000000000000000000000000000000000ce100000000000000000000000000000000000000000000000056bc75e2d631000000000000000000000000000000000000000000000000000008ac7230489e8000000000000000000000000000000000000000000000000000000000000000021c0
      initialize@0x4ec81af1:
        registryAddress: 0x000000000000000000000000000000000000ce10
        _penalty: 100000000000000000000
        _reward: 10000000000000000000
        _slashableDowntime: 8640
    value: 0
  5:
    contract: ElectionProxy
    function: _setImplementation
    args:
      0: 0xDEF73db69E5aaCcbC803ab89ef6b9a31CF5F4Ff0
    params:
      implementation: 0xDEF73db69E5aaCcbC803ab89ef6b9a31CF5F4Ff0
    value: 0
  6:
    contract: EpochRewardsProxy
    function: _setImplementation
    args:
      0: 0x274d63D315BfDd1A5c1409C1B1Ad1a88aeB07331
    params:
      implementation: 0x274d63D315BfDd1A5c1409C1B1Ad1a88aeB07331
    value: 0
  7:
    contract: EscrowProxy
    function: _setImplementation
    args:
      0: 0x372e54C597110Da170e96BF5baE3aABC367A9A18
    params:
      implementation: 0x372e54C597110Da170e96BF5baE3aABC367A9A18
    value: 0
  8:
    contract: ExchangeProxy
    function: _setImplementation
    args:
      0: 0x21b8dF5fBd0bcEf63Bef4f2cD22d4BCA4fFD3dEB
    params:
      implementation: 0x21b8dF5fBd0bcEf63Bef4f2cD22d4BCA4fFD3dEB
    value: 0
  9:
    contract: GasPriceMinimumProxy
    function: _setImplementation
    args:
      0: 0x011EC8fc4812daF3924A979A171C3Bb54D68B50c
    params:
      implementation: 0x011EC8fc4812daF3924A979A171C3Bb54D68B50c
    value: 0
  10:
    contract: GoldTokenProxy
    function: _setImplementation
    args:
      0: 0xa12d4bA7a4D5DAf29523eb87c519cb1dca6273F3
    params:
      implementation: 0xa12d4bA7a4D5DAf29523eb87c519cb1dca6273F3
    value: 0
  11:
    contract: GovernanceProxy
    function: _setImplementation
    args:
      0: 0xA92630F95a7Ec5EaFb791C93d60F4fa72EFa0e86
    params:
      implementation: 0xA92630F95a7Ec5EaFb791C93d60F4fa72EFa0e86
    value: 0
  12:
    contract: LockedGoldProxy
    function: _setImplementation
    args:
      0: 0x40cc4861e42a7867eC6d2De2800E9E1893fC3d07
    params:
      implementation: 0x40cc4861e42a7867eC6d2De2800E9E1893fC3d07
    value: 0
  13:
    contract: RandomProxy
    function: _setImplementation
    args:
      0: 0x876C992B4808E242E0113001FD51EA05790ed892
    params:
      implementation: 0x876C992B4808E242E0113001FD51EA05790ed892
    value: 0
  14:
    contract: ReserveProxy
    function: _setImplementation
    args:
      0: 0x330295A02E363e544c8C4ac8736A79Ba2DE382Bd
    params:
      implementation: 0x330295A02E363e544c8C4ac8736A79Ba2DE382Bd
    value: 0
  15:
    contract: SortedOraclesProxy
    function: _setImplementation
    args:
      0: 0xEFe7a08239Cd853383F4FD76e90616371096Efc7
    params:
      implementation: 0xEFe7a08239Cd853383F4FD76e90616371096Efc7
    value: 0
  16:
    contract: StableTokenProxy
    function: _setImplementation
    args:
      0: 0x4A1b48FC0ED957578EC697532b5c975fE94B6Ccf
    params:
      implementation: 0x4A1b48FC0ED957578EC697532b5c975fE94B6Ccf
    value: 0
  17:
    contract: ValidatorsProxy
    function: _setImplementation
    args:
      0: 0x3353c275FD5d37985cC5720C98E037f4dAE67301
    params:
      implementation: 0x3353c275FD5d37985cC5720C98E037f4dAE67301
    value: 0
metadata:
  proposer: 0x0Cc59Ed03B3e763c02d54D695FFE353055f1502D
  deposit: 10000000000000000000000 (~10000 10^18)
  timestamp: 1603826450
  transactionCount: 18
  descriptionURL: https://github.com/celo-org/celo-proposals/blob/master/CGPs/0013.md
stage: Queued
upvotes: 0
votes:
  Yes: 0
  No: 0
  Abstain: 0
passing: false
requirements:
  participation: 0.317813188295
  agreement: 90%
isApproved: false
isProposalPassing: false
secondsUntilStages:
  referendum: 14357
  execution: 100757
  expiration: 705557
```

**Comment by alecps** [comment]
Alfajores has been upgraded 🎉

**Comment by nambrot** [comment]
Mainnet has been executed! https://github.com/celo-org/celo-proposals/pull/85
