### ISSUE TITLE
Quality / bug fixing

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#4835]
- [ ] Continue addressing existing bugs and other minor improvements, see https://github.com/orgs/celo-org/projects/150
- [ ] Transaction feeds fixes (unknown, qr scan, etc) 
- [ ] Test iOS 14 beta (new API for clipboard monitoring

**Comment by gnardini** [comment]
Closing since it's an epic from a previous milestone
