### ISSUE TITLE
Address tech debt

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#4841]
- [ ] Consider using typed-redux-saga to fix recurrent issues with this
- [x] Continue removing obsolete code following the redesign
- [x] Simplify switch between envs (dev/prod)
