### ISSUE TITLE
QR code improvements

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#4849]
- [ ] adding the ability to request from a QR (this is send only after the redesign). this would involve changing behavior when scanning QR from the ‘request’ flow, no design changes
- [ ] deeplink updates so links work while the app is backgrounded (came from grameen brainstorm) — @yorhodes  has some more context on this, but he mentioned this would be easy
- [ ] since we now have links-- adding this link to the QR page per the new QR code page designs

**Comment by dominiquejane** [comment]
add:
- [ ] Deeplink should conditionally route to app/play store if the app not installed
