### ISSUE TITLE
Inventory of all infrastructure

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-monorepo#5386]
## Goal (Milestone 7)
- Have an understanding of what Kubernetes and VM infrastructure we run at cLabs. 
- Be able to use this data to make informed decisions about performance planning. 
- Be able to associate this data with the metrics inventory. 

Targeted Cloud Providers: 
- Google Cloud
  - [x] `celo-testnet` @aaronmboyd 
  - [x] `celo-testnet-production` @aaronmboyd 
  - [ ] Firebase projects, reach out to applications for details
-  [ ] AWS
- [ ] Azure

**Comment by aaronmboyd** [comment]
## Actions (from review session 16/12/2020)

- [ ] @jcortejoso  - celo-testnet - k8s workload - alfajoresstaging - alfajorestaging - Nodes (validator, proxy, attestation, postgreSQL) - Potentially delete
- [ ] @jcortejoso  - celo-testnet - k8s workload - alfajoresstaging - alfajorestaging - Bootnode - Potentially delete
- [ ] @jcortejoso  - celo-testnet - k8s workload - alfajoresstaging - alfajorestaging - Blockscout (indexer, crawler, migration, web) - Potentially delete
- [ ] @jcortejoso  - celo-testnet - k8s workload - alfajoresstaging - alfajorestaging - eksportisto - Potentially delete
- [ ] @jcortejoso  - celo-testnet - k8s workload - alfajoresstaging - default - Ingress (cert Manager / acme / nginx) - Potentially delete
- [ ] @jcortejoso  - celo-testnet - k8s workload - alfajoresstaging - alfajorestaging - CeloStats (frontend, server) - Potentially delete
- [ ] @jcortejoso  - celo-testnet - k8s workload - alfajoresstaging - alfajorestaging - Tx Nodes (nodes, private) - Potentially delete
- [ ] @jcortejoso  - celo-testnet - k8s workload - alfajoresstaging - prometheus - Prometheus - Potentially delete
- [ ] @jcortejoso  - celo-testnet - k8s workload - baklavastaging - default - Ingress (cert Manager / acme / nginx) - Potentially delete
- [ ] @jcortejoso  - celo-testnet - k8s workload - baklavastaging - baklavastaging - CeloStats (frontend, server) - Potentially delete
- [ ] @jcortejoso  - celo-testnet - k8s workload - baklavastaging - prometheus - Prometheus - Potentially delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - attestationtesting - Nodes (validator, proxy, attestation, postgreSQL) - attestationtesting-validators-1 CrashLoopBackoff
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - attestationtesting - Bootnode - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - attestationtesting - CeloStats (frontend, server) - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - attestationtesting - Tx Nodes (nodes, private) - Post for owner, prepare for delete
- [ ] @YoduYodu - celo-testnet - k8s workload - celo-networks-dev - hare2 - Bootnode - @jcortejoso  to contact owner
- [ ] @YoduYodu - celo-testnet - k8s workload - celo-networks-dev - hare2 - Nodes (validator, proxy) - @jcortejoso  to contact owner
- [ ] @YoduYodu - celo-testnet - k8s workload - celo-networks-dev - hare2 - Tx Nodes (nodes, private) - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - k8s workload - celo-networks-dev - nammetadata3 - Bootnode - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - k8s workload - celo-networks-dev - nammetadata3 - Nodes (validator, proxy, attestation, postgreSQL) - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - k8s workload - celo-networks-dev - nammetadata3 - Tx Nodes (nodes, private) - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - k8s workload - celo-networks-dev - nammetadata3 - Blockscout (indexer, crawler, migration, web) - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - k8s workload - celo-networks-dev - nammetadata3 - CeloStats (frontend, server) - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - k8s workload - celo-networks-dev - nammigrationtest2 - Bootnode - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - k8s workload - celo-networks-dev - nammigrationtest2 - Nodes (validator, proxy, attestation, postgreSQL) - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - k8s workload - celo-networks-dev - nammigrationtest2 - Tx Nodes (nodes, private) - @jcortejoso  to contact owner
- [ ] @tkporter - celo-testnet - k8s workload - celo-networks-dev - oracledev - Bootnode - 
- [ ] @tkporter - celo-testnet - k8s workload - celo-networks-dev - oracledev - Nodes (validators only) - 
- [ ] @tkporter - celo-testnet - k8s workload - celo-networks-dev - oracledev - Tx Nodes (nodes, private) - 
- [ ] @tkporter - celo-testnet - k8s workload - celo-networks-dev - pendingtx - Bootnode - Probably can delete
- [ ] @tkporter - celo-testnet - k8s workload - celo-networks-dev - pendingtx - Nodes (validator, proxy) - Probably can delete
- [ ] @tkporter - celo-testnet - k8s workload - celo-networks-dev - pendingtx - Tx Nodes (nodes, private) - Probably can delete - (Pods have warnings)
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - release1 - Bootnode - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - release1 - Nodes (validator, proxy) - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - release1 - Tx Nodes (nodes, private) - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - prometheus - Prometheus - 
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - prometheus - workload-identity-test - 
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - release1test - Nodes (validator, proxy) - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - release1test - Bootnode - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - release1test - CeloStats (frontend, server) - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - release1test - Tx Nodes (nodes, private) - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - release1test - Blockscout (indexer, crawler, migration, web) - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - releasetest - Bootnode - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - releasetest - Tx Nodes (nodes, private) - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - releasetest - Nodes (validator, proxy) - Post for owner, prepare for delete
- [ ]  - celo-testnet - k8s workload - celo-networks-dev - release-geth-sync - sync-test-75c938da22e23322983fd42bd2071fb59c5ccb0d - 
- [ ] Hernan - celo-testnet - k8s workload - celo-networks-dev - hbandura - sync-test-master - 
- [ ] @YoduYodu - celo-testnet - k8s workload - celo-networks-dev - tortoise2 - Nodes (validator, proxy) - @jcortejoso  to contact owner
- [ ] @YoduYodu - celo-testnet - k8s workload - celo-networks-dev - tortoise2 - Tx Nodes (nodes, private) - @jcortejoso  to contact owner
- [ ] @YoduYodu - celo-testnet - k8s workload - celo-networks-dev - tortoise2 - CeloStats (frontend, server) - @jcortejoso  to contact owner
- [ ] @YoduYodu - celo-testnet - k8s workload - celo-networks-dev - tortoise2 - Bootnode - @jcortejoso  to contact owner
- [ ] @tkporter - celo-testnet - k8s workload - celo-networks-dev - trevor4 - Bootnode - @tkporter to delete
- [ ] @tkporter - celo-testnet - k8s workload - celo-networks-dev - trevor4 - Nodes (validator, proxy) - @tkporter to delete
- [ ] @tkporter - celo-testnet - k8s workload - celo-networks-dev - trevor4 - Tx Nodes (nodes, private) - @tkporter to delete
- [ ] @tkporter - celo-testnet - k8s workload - celo-networks-dev - nightly-tools - Various geth sync triggers - 
- [ ] @jcortejoso  - celo-testnet - k8s workload - changeset - changeset - Tx Nodes (nodes, private) - Potential rename for purpose
- [ ] @jcortejoso  - celo-testnet - k8s workload - changeset - changeset - Bootnode - Potential rename for purpose
- [ ] @jcortejoso  - celo-testnet - k8s workload - changeset - changeset - CeloStats (frontend, server) - Potential rename for purpose
- [ ] @jcortejoso  - celo-testnet - k8s workload - changeset - changeset - Nodes (validator, proxy) - Potential rename for purpose
- [ ] @jcortejoso  - celo-testnet - k8s workload - changeset - default - Ingress (cert Manager / acme / nginx) - Potential rename for purpose
- [ ] @jcortejoso  - celo-testnet - k8s workload - changeset - prometheus - Prometheus / Grafana - Potential rename for purpose
- [ ] @tkporter - celo-testnet - k8s workload - federated-dev-asia-northeast2-a - default - Ingress (cert Manager / acme / nginx) - @tkporter to delete
- [ ] @tkporter - celo-testnet - k8s workload - federated-dev-asia-northeast2-a - oracledev - ?? - @tkporter to delete
- [ ] @tkporter - celo-testnet - k8s workload - federated-dev-asia-northeast2-a - prometheus  - Prometheus - @tkporter to delete
- [ ] @tkporter - celo-testnet - k8s workload - federated-dev-us-west-4 - default - Ingress (cert Manager / acme / nginx) - @tkporter to delete
- [ ] @tkporter - celo-testnet - k8s workload - federated-dev-us-west-4 - oracledev - ?? - @tkporter to delete
- [ ] @tkporter - celo-testnet - k8s workload - federated-dev-us-west-4 - prometheus  - Prometheus - @tkporter to delete
- [ ] @tkporter - celo-testnet - k8s workload - restore-us-east1 - restore-fullnodes - ?? - @tkporter to contact owner
- [ ] @tkporter - celo-testnet - VM - alexbh-test-node -  - ?? - @tkporter to contact owner
- [ ] @tkporter - celo-testnet - VM - client-log-all-envs-3-09300348-1ocj-harness-nj29 -  - ?? - @tkporter to contact owner
- [ ] @kobigurk - celo-testnet - VM - kobigurk-snark-tests -  - ?? - @tkporter to contact owner
- [ ] @kobigurk - celo-testnet - VM - kobigurk-test-sync-bug -  - ?? - @tkporter to contact owner
- [ ] Lucas - celo-testnet - VM - lucas-certora1 -  - ?? - @tkporter to contact owner
- [ ] @nambrot - celo-testnet - VM - nam-baklava-account-machine -  - ?? - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - VM - nam-baklava-attestation-machine -  - ?? - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - VM - nam-baklava-proxy-machine -  - ?? - @jcortejoso  to contact owner
- [ ] @nambrot - celo-testnet - VM - nam-baklava-validator-machine -  - ?? - @jcortejoso  to contact owner
- [ ]  - celo-testnet - VM - panic-debugging -  - ?? - Post for owner, prepare for delete
- [ ]  - celo-testnet - VM - sftp-server -  - ?? - Post for owner, prepare for delete
- [ ]  - celo-testnet - VM - snark-benchmark -  - ?? - Post for owner, prepare for delete
- [ ]  - celo-testnet - VM - test-metrics -  - ?? - Post for owner, prepare for delete
- [ ]  - celo-testnet - VM - validator-testing -  - ?? - Post for owner, prepare for delete
- [ ] Victor - celo-testnet - VM - victor-titan-validator -  - ?? - Post for owner, prepare for delete
- [ ] Volpe - celo-testnet - VM - volpe-public-markets-observer -  - ?? - 
- [ ] Audrey - celo-testnet - VM - yerduaoracletest -  - ?? - 
- [ ]  - celo-testnet - Cloud Function - handleVerificationRequestalfajoresstaging -  -  - Potential delete, deprecated
- [ ]  - celo-testnet - Cloud Function - handleVerificationRequestbaklavastaging -  -  - Potential delete, deprecated
- [ ]  - celo-testnet - Cloud Function - handleVerificationRequestintegration -  -  - Potential delete, deprecated
- [ ]  - celo-testnet - Cloud Function - handleVerificationRequestnamidentity26 -  -  - Potential delete, deprecated
- [ ]  - celo-testnet - Cloud Function - handleVerificationRequestpilotstaging -  -  - Potential delete, deprecated
- [ ]  - celo-testnet-production - VM - drand-1 -  - ?? - 
- [ ]  - celo-testnet-production - VM - rc0-releasegold-validator -  - ?? - Stopped, can delete
- [ ]  - celo-testnet-production - k8s workload - baklava - baklava - Leaderboard - Paused, potentially delete
- [ ]  - celo-testnet-production - k8s workload - baklava - baklava - Leaderboard2 - Paused, potentially delete
- [ ]  - celo-testnet-production - k8s workload - baklava - baklava - Baklava Oracle - Paused, potentially delete
- [ ] @jcortejoso  - celo-testnet-production - k8s workload - baklava - baklava - baklava-prom-to-sd - Double check with @jcortejoso , potential delete
- [ ]  - celo-testnet-production - k8s workload - baklava - baklava - Baklava voting bot - Paused, potentially delete
- [ ] @nambrot - celo-testnet-production - k8s workload - baklava - baklava - testnet-baklava-transaction-metrics-exporter - Double check with @nambrot, potential delete
- [ ] @jcortejoso  - celo-testnet-production - k8s workload - mainnet - rc1 - rc1-prom-to-sd - Double check with @jcortejoso , potential delete
- [ ] @nambrot - celo-testnet-production - k8s workload - mainnet - rc1 - rc1-transaction-metrics-exporter-1, 2 - Double check with @nambrot, potential delete
- [ ]  - celo-testnet-production - Cloud Function - handleVerificationRequestalfajores -  - ?? - Deprecated, delete
- [ ]  - celo-testnet-production - Cloud Function - handleVerificationRequestpilot -  - ?? - Deprecated, delete
- [ ] @jcortejoso  - celo-testnet-production - SQL - alfajores76263e86 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet-production - SQL - alfajores76263e86-405c-49be-9ffd-1596b9a1acc3 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet-production - SQL - alfajores8 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet-production - SQL - argentinaproduction -  - PostgreSQL 9.6 - Delete
- [ ] @jcortejoso  - celo-testnet-production - SQL - baklava1 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet-production - SQL - baklava2 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet-production - SQL - baklava3 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet-production - SQL - data-warehouse-prod -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet-production - SQL - pilot2 -  - PostgreSQL 9.6 - Delete
- [ ] @jcortejoso  - celo-testnet-production - SQL - pilot5 -  - PostgreSQL 9.6 - Delete
- [ ] @jcortejoso  - celo-testnet-production - SQL - rc01 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet-production - SQL - rc11 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet-production - SQL - rc12 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - SQL - alfajoresstaging16 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - SQL - attestationtesting -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - SQL - carter212 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - SQL - carter3 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - SQL - kevjuedelayedsigningtest -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - SQL - loadtest1 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - SQL - namemetadata32 -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - SQL - namerelease1test -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - SQL - release1test -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - SQL - yerdua -  - PostgreSQL 9.6 - Confirm if being used, delete otherwise
- [ ] @jcortejoso  - celo-testnet - Load Balancer - alexbh-valora-backend -  - Global lb - Confirm if being used, delete otherwise
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-alfajoresstaging-alfajoresstaging-celostats-ingress--f90 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-alfajoresstaging-alfajoresstaging-ethstats-ingress--f9b0 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-berlintestnet001-berlintestnet001-celostats-ingress--080 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-berlintestnet001-berlintestnet001-ethstats-ingress--0870 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-strakadelayedsigning-strakadelayedsigning-celostats-ser0 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-strakadelayedsigning-strakadelayedsigning-ethstats-ingr0 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-strakadelayedsigningsix-strakadelayedsigningsix-celosta0 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-strakadelayedsigningsix-strakadelayedsigningsix-ethstat0 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-strakadelayedsigningthree-strakadelayedsigningthree-cel0 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-strakadelayedsigningthree-strakadelayedsigningthree-eth0 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-strakadelayedsigningtwo-strakadelayedsigningtwo-celosta0 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-strakadelayedsigningtwo-strakadelayedsigningtwo-ethstat0 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-validatorconnset-validatorconnset-celostats-frontend--00 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-validatorconnset-validatorconnset-celostats-server--0870 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-validatorconnset-validatorconnset-ethstats-ingress--0870 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - k8s-um-yerduaoracletest-yerduaoracletest-ethstats-ingress--0870 -  - Global lb - Review and delete if necessary
- [ ] @tkporter - celo-testnet - Load Balancer - oracledev-forno-url-map -  - Global lb - Delete
- [ ] @tkporter - celo-testnet - Load Balancer - trevor-url-map -  - Global lb - Delete
