### ISSUE TITLE
Testing: Identify and fix testing coverage gaps in devX services

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#6152]
- Discussion
    - Review and explicitly define the tests we need across devX services
    - Which packages increase coverage
        - dappkit, explorer, governance, wallet-base, and wallet-hsm
    - Writing tests for those
    - Defining best practices
        - How are we writing tests across engineering?
        - Standardizing internal dev experience
- Why is this epic important?
    - Increased tests prevent bugs and increase developer confidence that things haven't been broken
- Definition of Done
    - [x]  Gaps in test coverage have been identified
    - [ ]  Coverage has increased in specified packages
    - [ ]  Best practices doc for testing is started

**Comment by medhak1** [comment]
No updates here afaik
