### ISSUE TITLE
Docs 2.0

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#6158]
Decrease engineering time to debugging Gitbook and auto-generated documentation.

Increased control over documentation layout and navigation
Improve contributor cycle.

### Definition of Done

- [x]  Users can access auto-generated documents
- [x]  New docs repo is setup
- [x] Contributors can make changes and load a local version of docs
- [ ] New docs site is deployed

**Comment by medhakothari** [comment]
weekly updates: set up the auto generated documents for all the new sdk packages, and generalized the existing script so that it can be used for any future package
