### ISSUE TITLE
CLI + CK: Improve CK install and bundle size

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#6193]
- Why is this epic important?
    - Reducing install time and bundle size improves client-side development experience and ability to run dapps on older devices
- Definition of Done
    - [x]  `utils` is divided into different packages
    - [x]  Library dependencies are reduced
    - [x]  Bundle size is smaller
- What's involved in completing this epic?

    Reduce install time (use on client-side applications) [10] 

    - Divide our `utils` (currently bigger than `web3`)
        - Couldn't do this before CK modularization
            - example: google phone numbers
        - Copy/paste if only using one function from a library
        - Some libraries are easy to extract, others are a little more involved
        - Break up `utils` similar to how `wallet-` got split up
        - e2e tests will break every time something is changed at this level
    - web3 1.3 (investigate)
        - Using crypto library and removing `nodegyp` install issues
        - Might be able to migrate some libraries and delete compiled dependencies
    - Ethers.js [backlog]
        - Bigger time investment
        - Later
    - Bug (permission issues) [0.5]
        - `bls` repo dependency (private)
            - easy fix: publish package at a version
            - dependency on this reduced with CK modularization

**Comment by aslawson** [comment]
Related Ticket: https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/celo-monorepo/4445

**Comment by medhakothari** [comment]
12% of the bundlesize of the contractkit pkg (see [here](https://bundlephobia.com/result?p=@celo/contractkit@1.0.2)) comes from the dependency on `moment` which is used in one tiny tiny line [here](https://github.com/celo-org/celo-monorepo/blob/fdf0d8b4a8ed27a47273b24a3875a896ed6e2a2c/packages/sdk/contractkit/src/wrappers/BaseWrapper.ts#L129), so that’s one small step we can take too
