### ISSUE TITLE
cEUR support for CLI

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6793]
CLI use cases that need updating
- [x] Transfer `celocli transfer:euros`
- [x] Exchange `celocli exchange:euros`
- [x] Gas currency `celocli config:set --gasCurrency cEUR`
- [ ] Check no cEUR balance before destroying ReleaseGold contracts `celocli releasegold:refund-and-finalize`

Detailed breakdown:
- Add cEUR to GasOption enum
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/base.ts#L14](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/base.ts#L14)
- Add logic for using cEUR as a gas currency
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/base.ts#L177](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/base.ts#L177)
- Create a transfer command for cEUR, similar to the existing one for cUSD
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/transfer/dollars.ts](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/transfer/dollars.ts)
    - May be good to figure out a way to share code between the dollars & euros command
- Add cEUR ↔ CELO (& vice versa) exchange rates for the `exchange show` command
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/exchange/show.ts](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/exchange/show.ts)
- Add cEUR `exchange:euros` command
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/exchange/dollars.ts](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/exchange/dollars.ts)
    - Generalize function `checkNotDangerousExchange` to work for a parametrized stable token
        - [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/utils/exchange.ts#L22](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/utils/exchange.ts#L22)
- Modify `exchange:celo` and `exchange:gold` to work with cEUR as well
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/exchange/celo.ts](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/exchange/celo.ts) and [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/exchange/gold.ts](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/exchange/gold.ts)
    - Currently, these commands assume you are exchanging CELO → cUSD. We could add a flag to indicate what currency you wish to buy. If backward compatibility is desired, we can consider making the flag optional and default to cUSD
- Update description for `account:balance` command to include cEUR
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/account/balance.ts#L6](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/account/balance.ts#L6)
    - With the relevant contractkit change already made, cEUR will print with no changes in the CLI required
- (Optional) add cEUR to list of examples for setting gas currency config
    - [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/config/set.ts#L22](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/config/set.ts#L22)
- Add StableTokenEUR as an option for oracle related commands
    - Would be good to consolidate all the different places that the options are defined into one variable
    - `oracle:list` [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/oracle/list.ts#L16](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/oracle/list.ts#L16)
    - `oracle:remove-expired-reports` [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/oracle/remove-expired-reports.ts#L16](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/oracle/remove-expired-reports.ts#L16)
    - `oracle:report` [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/oracle/report.ts#L18](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/oracle/report.ts#L18)
    - `oracle:reports` [https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/oracle/reports.ts#L18](https://github.com/celo-org/celo-monorepo/blob/master/packages/cli/src/commands/oracle/reports.ts#L18)

**Comment by clrblmt** [comment]
Added details to requirements

**Comment by asaj** [comment]
> Check no cEUR balance before destroying ReleaseGold contracts celocli releasegold:refund-and-finalize

Is this needed? IIUC this was to prevent contracts from being destroyed that may have accumulated cUSD validator rewards

**Comment by asaj** [comment]
What about `account:balance`?

**Comment by aslawson** [comment]
seems like economics team has taken most of this on, but not done in a generic stabletoken fashion. will create a separate ticket to generalize it.

@gastonponti will scope remaining work needed

**Comment by martinvol** [comment]
It is included on the ticket, but here's an example of how the cli handles `oracle:list` for an stableToken today
```
./packages/cli/bin/run oracle:list 0xcCA78ae41fe8F83eE7F37B0110eb6FAe3E9Ca0F0
(node:3956) ExperimentalWarning: The fs.promises API is experimental
Failed to close the connection: Error: Expected 0xcCA78ae41fe8F83eE7F37B0110eb6FAe3E9Ca0F0 to be one of: StableToken
See more help with --help
 ›   Error: Expected 0xcCA78ae41fe8F83eE7F37B0110eb6FAe3E9Ca0F0 to be one of: StableToken
 ›   See more help with --help
```

**Comment by martinvol** [comment]
We should also update these commands:
1. `celocli network:contracts`
2. `celocli network:parameters`

**Comment by barbaraliau** [comment]
@gastonponti is this item in the description complete?
 `Check no cEUR balance before destroying ReleaseGold contracts celocli releasegold:refund-and-finalize`

**Comment by aslawson** [comment]
Removed https://app.zenhub.com/workspaces/cap-backlog-board-600598462807be0011921c65/issues/celo-org/celo-monorepo/7157 from this epic as it is low priority and closing Epic as complete.
