### ISSUE TITLE
Fixes on DappKit based on feedback

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#841]
Feeback to resolve:

- [ ] ~~There isn't any comprehensive documentation of all available functions and their signatures and behaviors for dappkit~~ Out of scope for now, raised #860
- [ ] ~~There are warnings when using the SDK which the documentation just tells us to ignore. While the yellow box can be hidden, the console output gets polluted.~~ Out of scope, as that is mostly a problem of dependencies, not dappkit
- [ ] ~~SECURITY RISK: when requesting for the account address, cancelling the request on the Celo Wallet app still yields the address and phone number~~ Out of scope, raised #757 
- [ ] ~~When requesting for the account address, regardless of the dApp name submitted, the Celo wallet always refers to the connecting app as "Savings Circle"~~ Out of scope, issue is #758 
- [x] Typescript definitions do not match what is actually accepted by functions such as requestTxSig, forcing us to suppress typescript errors. For example, when signing a transaction for contract deployment kit.web3.eth.Contract(...).deploy(...), only from and tx are necessary when signing.
