### ISSUE TITLE
ODIS 2.0.0 (CIP-40) Refactor Implementation

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#8645]
- [x] celo-org/celo-monorepo#9717 
- [x] celo-org/celo-monorepo#9716 
- [x] celo-org/celo-monorepo#9719 
- [x] celo-org/celo-monorepo#9703 
- [x] celo-org/celo-monorepo#9757 
- [x] celo-org/celo-monorepo#9758 
- [x] celo-org/celo-monorepo#9759 
- [x] celo-org/celo-monorepo#9792 
- [x] celo-org/celo-monorepo#9793 
- [x] celo-org/celo-monorepo#9794 
- [x] celo-org/celo-monorepo#9795 
- [x] celo-org/celo-monorepo#9796 
- [x] celo-org/celo-monorepo#9800 
- [x] celo-org/celo-monorepo#9801 
- [x] celo-org/celo-monorepo#9803 
- [x] celo-org/celo-monorepo#9804
- [x] celo-org/celo-monorepo#9805
- [x] celo-org/celo-monorepo#9806 
- [x] celo-org/celo-monorepo#9808
- [x] celo-org/social-connect#70
- [x] celo-org/celo-monorepo#9811 
- [x] celo-org/celo-monorepo#9812
- [x] celo-org/celo-monorepo#9813 
- [x] celo-org/celo-monorepo#9814 
- [x] celo-org/celo-monorepo#9836 
- [x] celo-org/celo-monorepo#9837 
- [x] celo-org/celo-monorepo#9845
- [x] celo-org/social-connect#18
- [x] celo-org/celo-monorepo#9859 
- [x] celo-org/celo-monorepo#9862
- [x] celo-org/celo-monorepo#9863 
- [x] celo-org/celo-monorepo#9818
- [x] celo-org/celo-monorepo#7280 
- [x] celo-org/celo-monorepo#9729 
- [x] celo-org/celo-monorepo#9869

**Comment by alecps** [comment]
- any type casting would be better as an io-ts check

**Comment by arthurgousset** [comment]
- [x] @alecps - Will split this out into various tickets

**Comment by arthurgousset** [comment]
@alecps during sprint planning:
- [x] will fill out body to split this into todo check boxes
- changed directory structure (pretty big change in git)
- synced with @nategraf on tests (basically finished signer testing)
- unfortunately combiner tests are harder
- will probably take whole sprint

**Comment by arthurgousset** [comment]
@alecps during sprint planning: 

- this is going to be a major upgrade and include not only CIP40 support but also work that @eelanagaraj is doing on rate-limiting too
- possibly includes going over the code and see other things to refactor

**Comment by arthurgousset** [comment]
0
