### ISSUE TITLE
[Account Recovery] Primitive: Password Hardening (Phase 1)

### ISSUE THREAD

**Issue by ag-clabs** [celo-org/celo-monorepo#8743]
# Context

This epic is to help us coordinate "phase 1" of account recovery.

🚧 _This is a WIP and not to be taken as guidance. It's mostly to help me think about the initiative (sort of like a brain dumb_ 😅) 

💬 _Please (🙏) comment or edit this description to correct me where I'm **wrong**._

**Reference**

- larger epic "[Valora account recovery](https://app.zenhub.com/workspaces/celo-5d94ef61d9b1e40001114c02/issues/celo-org/celo-monorepo/7240)"

**Tickets**

- [ ] @arthurgousset + @nategraf: Add tickets to this epic to complete the below action items

# Parts

## 1. Education

*Goal?*

- Bring stakeholders up to speed with our "vocabulary" and infrastructure

*How*?

- Combination of **blog post**, YouTube **Tech Talk**
- Simplified **diagrams** to visualise the request flow betwee ODIS, wallet, and SDK (+ anything I missed)

*Why?*

- So that **calls** with wallets can be more insightful and opinionated

*Observation*:

- From the wallet council, it seems like wallets don't have strong views on their fully fledged approach to account recovery, because
  1. they haven't **thought** all that much about it, and
  2. perhaps because they don't understand our **infrastructure** (ODIS and Komenci among other things) well enough

Action items:

- [ ] Connect @nategraf  with with Victoria (MarComm) to coordinate **blog post**
- [ ] Connect @nategraf  with Judy to coordinate **Tech Talk**

## 2. Impact Assessment (just for context)

- [ ] Assess current Valora need (e.g. "how many account recovery tickets does Valora have", i.e. how pressing an issue is this today)

## 3. Scope/Need Gathering (wallet calls)

*Goal* 

- Conduct wallet **calls** to understand their most "basic" needs (what should our scope be)

*How*?

- [ ] @arthurgousset : share blog post and tech talk as **primer** ahead of call
- [ ] @arthurgousset + @nategraf : Interview wallets to assess their current needs/approach to account recovery

*Why?*

- Because wallet adoption of identity primitives is one of our success metrics.

*Observation*:

- From the wallet council: wallets like Trustworks (Alesh), SteakWallet (Alex), and Celo Wallet (Rossy) expressed interest in a composable recovery solution ("**pick and choose**"), sort of highlighting that they would be interested in parts of the solution (e.g. password hardening while storage is handled by wallets)

## 4. Implementation

_ODIS_

- [ ] @arthurgousset: Get up to speed on current **status** with ODIS part to password hardening

_SDK_

- [ ] @nategraf: Spec out **tickets** for library implementation of password hardening on ZenHub.

## 5. Adoption

- [ ] [Potentially/Idea] Refactor Figment drawingsl, so the edge cases and complete user flow can be shared with wallets as guidance
- [ ] Share @nategraf blog post, tech talk, documentation (for devs)
- [ ] Set up first call with interested wallets (to run through basics)
- [ ] [Potentially/Idea] Set up account recovery "help desk" (once a week office hour) where devs can come and pick Victor's brain

**Comment by arthurgousset** [comment]
Collecting wallets we want to speak to: 

- [ ] KotaniPay
- [ ] Kaala

@nategraf Please feel free to add more below so we can track the progress.

**Comment by nategraf** [comment]
@arthurgousset I went ahead and added all the wallets I think would be interested. (I notably left out Celo Wallet and Celo Terminal, because I think they are less interested in account recovery solutions for the moment and have different constraints on desktop.)

**Comment by 0xarthurxyz** [comment]
Closing this epic, because it was never realised used.
