### ISSUE TITLE
Update attestation docs

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#8745]
## Context

I get a lot of requests (during office hours and in other calls) for simple explanations of the request flow from phone number **verification** to phone number **mapping** (sort of explaining the problems the **attestation service** and **ODIS** are solving).

- [x] @arthurgousset: Visualising request flow using a diagran
- [ ] record a loom video to ELI5 how phone number verifications and mappings work at Celo

Todo: 
- [x] learn how to modify docs.celo.org with @critesjosh 

Questions: 
- Explain changing phone number (AS/ODIS flows)
