### ISSUE TITLE
[Account Recovery] Primitive: Smart Contract Wallet (Phase 2)

### ISSUE THREAD

**Issue by ag-clabs** [celo-org/celo-monorepo#8759]
This epic is to help us coordinate "phase 1" of account recovery.

🚧 _This is a WIP and not to be taken as guidance. It's mostly to help me think about the initiative (sort of like a **brain dumb** 😅)_ 

💬 _Please (🙏) comment or edit this description to correct me where I'm **wrong**._

**Reference**

- larger epic "[Valora account recovery](https://app.zenhub.com/workspaces/celo-5d94ef61d9b1e40001114c02/issues/celo-org/celo-monorepo/7240)"

**Tickets**
- [ ] @arthurgousset: Add ticket to this epic to complete the below action items.

# Parts

## 1. Impact Assessment

*Goal?*

- Assess major wallet's interest for smart contract wallets (**komenci**) in the context of account recovery

*How*?

- Wallet **calls**

*Why?*

- So that we can assess who might want to use our primitive and prioritise
  1. how much time to allocate to **design** and **implementation** work, and
  2. **ownership** komenci going forward

*What?* 

- [x] @codyborn: Add wallets that we might consider important stakeholders here

## Wallets (running status)

- [ ] Valora: @arthurgousset to collect background from @nategraf / @codyborn / @aslawson on Valora's stance
- [ ] Opera: @arthurgousset to sync with @nategraf / @codyborn / @timmoreton on reaching out to check their appetite
- [ ] Trustworks: @arthurgousset to sync with @codyborn on their use case
- [ ] Mozilla: @aslawson is probably the person to talk to. I believe they're interested in a MTW feature which would allow account linking.. multiple signers for one account.
- [ ] TMobile/Deutsche Telekom: I'd sync with `Julia Carbajal` on these.
- [ ] CBDC wallet? Ezechiel Copic is the best person to reach out to.

**Comment by arthurgousset** [comment]
Added reference to larger epic "[Valora account recovery](https://app.zenhub.com/workspaces/celo-5d94ef61d9b1e40001114c02/issues/celo-org/celo-monorepo/7240)" pointed out by @nategraf on Slack

**Comment by 0xarthurxyz** [comment]
Closing this epic, because it was never used and the only ticket in is complete.
