### ISSUE TITLE
Release Attestation Service v1.5.0

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#8817]
Should include:
- feature: Verify by country
- bugfix: EIP712 signing
- bugfix: Verify API resend

Update release docs appropriately, see #9141

Make sure to include country provider setting recs in forum post!

# TODOs
- [x] bundle this with any Espresso HF upgrades to alfajores deployment
- [x] update package version of attestation service (do this in two commits pushed to master, then tag one as the AS release branch?)
  - [x] -> 1.5.0
  - [x] ->1.6.0-dev
- [x] make sure image builds locally
- [x] look into the Valora e2e test instructions and update
  - [x] talked to Valora folks about this -- e2e in CI in progress
  - [x] iOS e2e tests pass
  - [x] update runbooks accordingly
- [x] update docker image tags (on GCP)
- [x] draft release on GitHub
  - [x] publish release on GitHub
- [x] coordinate on a forum post about this (not urgent but recommended as this fixes several bugs that are expected to improve verification completion rates)
  - [ ] follow up on this
- [x] post on Discord about this
- [x] update runbooks for release process
- [x] update docs (pre-merge, auto-format doc as well)
- [x] update release branch
