### ISSUE TITLE
Clean up "Stakeholder list" and "stakeholder docs tracker" (in stakeholder research)

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#8949]
# Context

I documented my early ramping up/readings into identity below. It's a little antiquated now, but I'll clean it up and link it in the ID notion page.

- [Stakeholders](https://www.notion.so/clabsco/749d6798761448fd91756667409a77de?v=2408c5b2e5a7437cbcc929340f76a8ec)
- [Stakeholder docs](https://www.notion.so/clabsco/6e817eec0d32474ab389aa9efe5c47e9?v=1191939b30d9474180411b0dd2d4dc39)

# Housekeeping

- [x] Clean up stakeholders (simplify table)
- [x] Clean up stakeholder docs page
- [x] Link in ID notion page

**Comment by arthurgousset** [comment]
Made good progress today but making stakeholder labelling meaningful and adding new stakeholders takes time.
