### ISSUE TITLE
[Tracking] Investigate low verification completion rate in BR

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9145]
[relevant slack thread](https://celo-org.slack.com/archives/CJXJ1EV0D/p1640156533390200)
Brazil rates investigation is documented here [🇧🇷 Brazil success rate (Marek’s query) ](https://www.notion.so/clabsco/Brazil-17-success-rate-Marek-s-query-256da82bea8d44928ac7a63ff0bdbb65#85abd9b941754dc6a7746ad5b84836de) for future reference

According to the Valora dashboards, Brazil has an extremely low verification rate. We cannot verify this against our own dashboards at the moment seemingly due to missing (or corrupted data) eksportisto 14 data.

TODOs for this ticket:
- [x] identify what is going on with missing eksportisto data -- does migrating to the maintained eksportisto solve these issues? if so, prioritize [this ticket](https://app.zenhub.com/workspaces/identity-sprint-board-61015de9a849530010b49fc6/issues/celo-org/celo-monorepo/9051)
- [x] can we reproduce the numbers seen in Valora? if not, how large is the discrepancy and where does it come from?
- [x] come up with sensible next steps regarding BR attestation rates -- what further data explorations would be helpful? Can we come up with a list of questions/possible factors to look at and see if we find anything useful here? 
- [x] make sure this investigation is well-documented so others can follow/understand stuff afterwards as well
- [x] (edit: added this cc @arthurgousset) follow up on original slack post to make sure everyone is on the same page
- [x] #9180

**Comment by eelanagaraj** [comment]
Indeed looks like an issue with eksportisto 14 not receiving data properly. Initial work on migrating the attestation service views to the new, maintained eksportisto seems to resolve the issue at the very least. Prioritizing #9051 to fix step one.

**Comment by 0xarthurxyz** [comment]
Brazil rates investigation is documented here [🇧🇷 Brazil success rate (Marek’s query) ](https://www.notion.so/clabsco/Brazil-17-success-rate-Marek-s-query-256da82bea8d44928ac7a63ff0bdbb65#85abd9b941754dc6a7746ad5b84836de) for future reference

**Comment by 0xarthurxyz** [comment]
Ticking off the todos in the description at the top

**Comment by 0xarthurxyz** [comment]
Added this ticket #9180 for future reference. 

------Copy of ticket-------
Mila pointed out that one possible reason for our lower success rate in Brazil could be due to misrecognised phone numbers. According to Mila (wikipedia below), the number of digits in a phone number increased from 8 to 9 to expand the set of phone numbers.

From [wikipedia](https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil#Ninth_digit_for_mobile_numbers):
> Brazilian mobile phone numbers always have nine digits now, but seven digits were usual in the first years, then eight digits became the standard for several years

- [ ] Check whether this could be a reason for lower success rates (relevant [Slack thread](https://celo-org.slack.com/archives/CJXJ1EV0D/p1640209027390800?thread_ts=1640156533.390200&cid=CJXJ1EV0D))
---------------------------

**Comment by 0xarthurxyz** [comment]
Closing this ticket because followed up on [Slack thread](https://celo-org.slack.com/archives/CJXJ1EV0D/p1642509316055200?thread_ts=1640156533.390200&cid=CJXJ1EV0D)
