### ISSUE TITLE
[Tracking] Set up Github project to facilitate backlog grooming and working in the open

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/celo-monorepo#9289]
Github project: 
- [x] Set up [Github project](https://github.com/orgs/celo-org/projects/164/)
- [x] Create meaningful tabs and categories
- [x] Add "estimate" txt field

Backlog grooming: 
- [x] #9319
- [x] #9320

Nice to have: 
- Consider adding "slacklog" (nice to have stuff)
- Good first tickets
  - Learn more about bounties (check with @joenyzio)

**Comment by 0xarthurxyz** [comment]
Closing this ticket, because it's complete and Github Projects is deprioritised.
