### ISSUE TITLE
[Tracking] Rotate ODIS signers

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#9314]
Prep work (while ago): 
- [x] https://github.com/celo-org/celo-monorepo/issues/8672
- [x] https://github.com/celo-org/celo-monorepo/issues/8355
- [x] https://github.com/celo-org/celo-monorepo/issues/8148
- [x] https://github.com/celo-org/celo-monorepo/issues/8186
- [x] https://github.com/celo-org/celo-monorepo/pull/8847
  - [x] https://github.com/celo-org/celo-monorepo/issues/8149
- [x] https://github.com/celo-org/celo-monorepo/issues/6685

Todos: 
- [x] https://github.com/celo-org/celo-monorepo/issues/8187
- [x] https://github.com/celo-org/celo-monorepo/issues/8046
- [x] celo-org/0xarthurxyz-pm-sandbox#90
- [x] celo-org/celo-monorepo#9343
- [x] celo-org/celo-monorepo#9342
- [x] celo-org/0xarthurxyz-pm-sandbox#87

**Comment by alecps** [comment]
closing this in favor of https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/9373

**Comment by arthurgousset** [comment]
Link to Github ticket instead of Zenhub ticket (for reference): 
- https://github.com/celo-org/celo-monorepo/issues/9373
