### ISSUE TITLE
Shepherd Core Contracts 8 Release

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#9711]
Github issue to keep track checklist in [Core Contracts release process](https://docs.celo.org/community/release-process/smart-contracts#promotion-process). 

T:

- [x] @0xarthurxyz: Create a Github issue tracking all these checklist items as an audit log
  - This is it: #9711
- [x] @0xarthurxyz: Implement the [git management steps](https://docs.celo.org/community/release-process/smart-contracts#When-a-new-release-branch-is-cut) for when a new release branch is cut.
  - **Release branch**:
  - > A new release branch is created release/core-contracts/${N} with the contracts to be audited.
  - > there already exists a release/core-contracts/8 branch, but it's deprecated - can be deleted and a new one of the same name be created at your release branch. [~Source: @m-chrzan]
  - Commands used (for review):
    ```bash
    git push origin --delete release/core-contracts/8 # delete existing release/core-contracts/8 branch (advised by Martin)
    git checkout origin/ASv2 # moves to development branch
    git branch release/core-contracts/8 # creates release branch
    git checkout release/core-contracts/8 # moves to release branch
    git log # checks last commit on release branch is as expected
    git push origin release/core-contracts/8 # publishes release branch
    ```
    - [x] this is the release branch: [`release/core-contracts/8`](https://github.com/celo-org/celo-monorepo/commits/release/core-contracts/8) (cut from our development branch [`ASv2`](https://github.com/celo-org/celo-monorepo/tree/ASv2/packages/protocol/contracts/identity), last commit `c1bd0574`)
    
  - **Tag commit**:
  - > The latest commit on the release branch is tagged with `core-contracts.v${N}.pre-audit`.
  - Commands used (for review):
    ```bash
    git log # check commits on release branch
    git show core-contracts.v8.pre-audit # checks if tag already exists (it does, Eela already tagged it)
    ```
    - [x] this is the tag: [`core-contracts.v8.pre-audit`](https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v8.pre-audit) for commit `c1bd0574`
  - **Update config.yml**:
  - > On master branch, [`.circleci/config.yml`](https://github.com/celo-org/celo-monorepo/blob/c1bd057484c4601436eb35c563d431f80d5f94b6/.circleci/config.yml#L37) should be edited so that the variable `RELEASE_TAG` points to the tag `celo-core-contracts-v${N}.pre-audit` so that all future changes to master are versioned against the new release. ~ Source: [Git release management](https://docs.celo.org/community/release-process/smart-contracts#when-a-new-release-branch-is-cut) 
  - > On the release branch, it should remain `core-contracts.v7`. [~Source: @m-chrzan]
  - Commands used (for review):
     ```bash
     # currently on master branch in monorepo
     git branch 0xarthurxyz/modify-circleci-configyml-for-CoreContracts8Release # makes branch for my 1 line change
     git checkout 0xarthurxyz/modify-circleci-configyml-for-CoreContracts8Release # moves to my branch
     # made 1 line change
     # committed to my branch (in VS Code UI)
     # pushed my branch to remote (in VS Code UI)
     # created PR in Github UI
     ```
    - [x] this is the PR: https://github.com/celo-org/celo-monorepo/pull/9734
  - **Pre-release notes**:
  - > On Github, a pre-release Github release should be created pointing at the latest tag on the release branch. ~ Source: [Git release management](https://docs.celo.org/community/release-process/smart-contracts#when-a-new-release-branch-is-cut)
  - Followed official Github instructions here: [Managing releases in a repository](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
)
    - [x] this is the pre-release: [Core Contracts Release 8](https://github.com/celo-org/celo-monorepo/releases/tag/core-contracts.v8.pre-audit)
- [x] @eelanagaraj: Submit release branch to a reputable third party **auditor for review**.
  - Completed with Hacken.io
- **Begin drafting release notes.**
  - [x] #9724

T+1w:

- [x] Receive report from auditors.
- [x] @0xarthurxyz: Add audit summary to final draft of the release notes.
- If all issues in the audit report have straightforward fixes:
  - **CGP**:
  - [ ] @0xarthurxyz: Submit a governance proposal draft
    - Started the CGP draft on this branch: [0xarthurxyz/cgp-61-core-contracts-8](https://github.com/celo-org/governance/tree/0xarthurxyz/cgp-61-core-contracts-8)
    - Added: [cgp-0061.md](https://github.com/celo-org/governance/blob/0xarthurxyz/cgp-61-core-contracts-8/CGPs/cgp-0061.md) (following example of Core Contract 7 release: [cgp-0055.md](https://github.com/celo-org/governance/blob/main/CGPs/cgp-0055.md))
    - Added: [cgp-0061.json](https://github.com/celo-org/governance/blob/0xarthurxyz/cgp-61-core-contracts-8/CGPs/cgp-0061/cgp-0061.json) (following example of Core Contract 7 release: [cgp-0055.json](https://github.com/celo-org/governance/blob/main/CGPs/cgp-0055/cgp-0055.json))
  - **`.json` file for CGP**:
  - [x] @alecps: Add any initialization data to the CGP that should be included as part of the proposal
  - **Forum post**:
  - [x] @0xarthurxyz: Announce forthcoming smart contract release on: https://forum.celo.org/c/governance
    - Created draft forum post: [Core Contracts Release 8 [DRAFT]](https://forum.celo.org/t/core-contracts-release-8-draft/4050) 
  - [x] Present "_Core Contract Release 8_" at Celo Governance Call
    - https://github.com/celo-org/governance/issues/164
- [x] @eelanagaraj: Commit audit fixes to the release branch
  - This is the release branch: https://github.com/celo-org/celo-monorepo/tree/ASv2/packages/protocol/contracts/identity
- [x] Submit audit fixes to auditors for review.
  - Completed with: #9678 
- [x] @alecps: Tag the first release candidate commit according to the [git release management instructions](https://docs.celo.org/community/release-process/smart-contracts#During-the-release-proposal-stage).
- [x] @0xarthurxyz: Let the community know about the upcoming release proposal by posting details to the Governance category on https://forum.celo.org and cross post in the [Discord #governance channel](https://discord.com/channels/600834479145353243/704805825373274134).See the 'Communication guidelines' section below for information on what your post should contain.

T+2w

- [ ] @alecps: On Tuesday: Run the smart contract release script in order to to deploy the contracts to Baklava as well as submit a governance proposal.
  - [ ] @0xarthurxyz: Transition proposal through Baklava governance process.
  - [ ] @0xarthurxyz: Update your forum post with the Baklava `PROPOSAL_ID`, updated timings (if any changes), and notify the community in the [Discord #governance channel](https://discord.com/channels/600834479145353243/704805825373274134).

T+3w

- [ ] @alecps: Confirm all contracts working as intended on Baklava.
- [ ] @alecps: Run the [smart contract release script](https://docs.celo.org/community/release-process/smart-contracts#release-process) in order to to deploy the contracts to Alfajores as well as submit a governance proposal.
- [ ] @0xarthurxyz: Update your forum post with the Alfajores `PROPOSAL_ID`, updated timings (if any changes), and notify the community in the [Discord #governance channel](https://discord.com/channels/600834479145353243/704805825373274134).

T+4w

- [ ] @alecps: Confirm all contracts working as intended on Alfajores.
- [ ] @0xarthurxyz: Confirm audit is complete and make the release notes and forum post contain a link to it.
- [ ] @alecps: On Tuesday: Run the [smart contract release script](https://docs.celo.org/community/release-process/smart-contracts#build-process) in order to to deploy the contracts to Mainnet as well as submit a governance proposal.
- [ ] Update the corresponding governance proposal with the updated on-chain `PROPOSAL_ID` and mark CGP status as `"PROPOSED"`.
- [ ] @0xarthurxyz: Update your forum post with the Mainnet `PROPOSAL_ID`, updated timings (if any changes), and notify the community in the [Discord #governance channel](https://discord.com/channels/600834479145353243/704805825373274134).
- At this point all stakeholders are encouraged to [verify](https://docs.celo.org/community/release-process/smart-contracts#verify-release-process) the proposed contracts deployed match the contracts from the release branch.
- [ ] @0xarthurxyz: Monitor the progress of the proposal through the [governance process](https://docs.celo.org/celo-codebase/protocol/governance).
  - Currently the governance process should take approximately 1 week: 24 hours for the dequeue process, 24 hours for the approval process, and 5 days for the referendum process. After which, the proposal is either declined or is ready to be executed within 3 days.
  - For updated timeframes, use the celocli: `celocli network:parameters`

T+5w

- If the proposal passed:
  - [ ] @alecps: Confirm all contracts working as intended on Mainnet.
  - [ ] @0xarthurxyz: Update your forum post with the Mainnet governance outcome (`Passed` or `Rejected`) and notify the community in the [Discord #governance channel](https://discord.com/channels/600834479145353243/704805825373274134).
  - [ ] @0xarthurxyz: Change corresponding CGP status to `EXCECUTED`.
  - [ ] @alecps: Merge the release branch into `master` with a merge commit
- If the proposal failed:
  - Change corresponding CGP status to `EXPIRED`.
